#!/usr/bin/env python3
"""Replace cycle3 jeux in jeux-suppleance.js"""

filepath = '/Users/admin/PROJETS_CLAUDE/app-suppleance/jeux-suppleance.js'

with open(filepath, 'r') as f:
    content = f.read()

# Find the cycle3 jeux array boundaries
# The array starts after "jeux: [" on the line following cycle3's icon line
marker_start = '    jeux: [\n'
# Find the cycle3 section first
cycle3_pos = content.index('cycle3: {')
# Find the jeux: [ after cycle3
jeux_start = content.index(marker_start, cycle3_pos)
array_content_start = jeux_start + len(marker_start)

# Find the closing ] of the jeux array
# It's "    ]" followed by newline
closing_bracket = content.index('\n    ]\n', array_content_start)

old_games = content[array_content_start:closing_bracket]
print(f"Found {old_games.count(chr(10))} lines of old games to replace")

new_games = r"""// ===== POURSUITE (20 jeux) =====
{cat:"Poursuite",titre:"Traque Royale",desc:"Délimitez le gymnase avec des cônes en créant des corridors et zones. Un joueur porte un dossard et devient le traqueur. Au signal, tous les autres se dispersent dans le labyrinthe. Chaque joueur touché enfile un dossard et devient traqueur à son tour. Le dernier survivant gagne et devient le premier traqueur de la prochaine manche. Variante : les traqueurs doivent se déplacer en marchant rapide seulement.",duree:"15 min",materiel:"Cônes, dossards",intensite:"Élevé"},
{cat:"Poursuite",titre:"La Meute de Loups",desc:"Désignez 3 joueurs comme loups avec des dossards. Tous les autres (caribous) se placent sur un mur du gymnase. Au signal, les caribous doivent traverser le gymnase pour atteindre le mur opposé sans se faire toucher. Les loups doivent communiquer et coordonner leurs déplacements pour encercler les caribous. Chaque caribou touché rejoint la meute. Le dernier caribou survivant choisit les 3 loups de la prochaine partie.",duree:"12 min",materiel:"Dossards",intensite:"Élevé"},
{cat:"Poursuite",titre:"Infection Zombie",desc:"Un joueur est désigné zombie patient zéro et porte un dossard vert. Les autres joueurs se dispersent dans le gymnase. Le zombie marche les bras tendus et touche les joueurs pour les contaminer. Chaque joueur touché devient zombie et doit aussi marcher bras tendus. Les survivants peuvent se réfugier dans une zone de sauvetage (cerceau) pour être immunisés pendant 10 secondes. Le jeu se termine quand tous sont zombies ou après 5 minutes.",duree:"15 min",materiel:"Dossards verts, cerceaux",intensite:"Élevé"},
{cat:"Poursuite",titre:"Chasseurs de Drapeaux",desc:"Divisez le gymnase en deux territoires avec une ligne centrale. Chaque équipe cache un drapeau (foulard) dans son territoire. Les joueurs doivent infiltrer le territoire adverse pour capturer le drapeau et le ramener de leur côté. Si un joueur est touché en territoire ennemi, il est prisonnier et doit rester immobile jusqu'à ce qu'un coéquipier le touche pour le libérer. L'équipe qui capture le drapeau adverse gagne.",duree:"15 min",materiel:"Foulards, cônes, dossards",intensite:"Élevé"},
{cat:"Poursuite",titre:"Sprint Commando",desc:"Formez deux équipes avec dossards de couleurs différentes. Chaque équipe a une prison (zone marquée par des cônes). Les joueurs tentent de toucher les adversaires pour les envoyer en prison. Un prisonnier peut être libéré si un coéquipier réussit à toucher sa main sans se faire attraper. Chaque joueur capturé vaut 1 point. L'équipe avec le plus de captures après 10 minutes gagne. Variante : ajouter des zones de refuge temporaire de 5 secondes.",duree:"15 min",materiel:"Dossards, cônes",intensite:"Élevé"},
{cat:"Poursuite",titre:"Le Kraken",desc:"Un joueur se place au centre du gymnase comme le Kraken. Tracez un cercle de 3 mètres autour de lui avec des cônes. Tous les autres joueurs doivent traverser le gymnase d'un mur à l'autre en passant dans la zone du Kraken. Le Kraken peut se déplacer uniquement dans son cercle. Tout joueur touché dans la zone devient une tentacule fixe qui peut aussi toucher les passants. Le dernier joueur libre gagne.",duree:"10 min",materiel:"Cônes",intensite:"Élevé"},
{cat:"Poursuite",titre:"Évasion Alcatraz",desc:"Placez 4 gardiens avec dossards dans la zone centrale du gymnase délimitée par des cônes. Les prisonniers partent tous d'un coin et doivent atteindre le coin opposé sans se faire toucher par un gardien. Les gardiens ne peuvent pas quitter la zone centrale. Les prisonniers attrapés s'assoient sur place et deviennent des obstacles. Après chaque manche, changez les gardiens. L'équipe de gardiens qui capture le plus de prisonniers gagne.",duree:"12 min",materiel:"Dossards, cônes",intensite:"Élevé"},
{cat:"Poursuite",titre:"Poursuite Stratégique",desc:"Divisez la classe en 3 groupes : les rouges poursuivent les bleus, les bleus poursuivent les jaunes, les jaunes poursuivent les rouges (comme roche-papier-ciseaux). Chaque joueur touché par son prédateur doit s'asseoir 10 secondes avant de repartir. Après 3 minutes, comptez les touches de chaque équipe. L'équipe avec le plus de touches gagne la manche. Variante : changer les rôles de prédateur à chaque manche.",duree:"12 min",materiel:"Dossards 3 couleurs",intensite:"Élevé"},
{cat:"Poursuite",titre:"Le Fugitif",desc:"Un seul joueur est le fugitif et a 10 secondes d'avance pour se cacher ou fuir dans le gymnase. Tous les autres sont des chasseurs. Le fugitif doit survivre 2 minutes sans se faire toucher. S'il réussit, il gagne. S'il est attrapé, le chasseur qui l'a touché devient le prochain fugitif. Placez des obstacles (bancs, tapis, cônes) pour créer des cachettes et des passages.",duree:"10 min",materiel:"Cônes, bancs, tapis",intensite:"Élevé"},
{cat:"Poursuite",titre:"Course au Trésor",desc:"Placez 20 objets (sacs de fèves, balles) dans un cerceau central. Les joueurs sont en 4 équipes, chacune dans un coin du gymnase avec un cerceau vide. Au signal, un joueur par équipe court au centre pour rapporter un objet. Quand le centre est vide, les joueurs peuvent voler dans les cerceaux adverses. Un gardien par équipe protège son cerceau en touchant les voleurs. L'équipe avec le plus d'objets après 5 minutes gagne.",duree:"12 min",materiel:"Sacs de fèves, balles, cerceaux, cônes",intensite:"Élevé"},
{cat:"Poursuite",titre:"Les Agents Secrets",desc:"Deux joueurs sont des agents secrets (ils ne savent pas qui est l'autre). Tous les joueurs marchent calmement dans le gymnase. Au signal, les agents doivent toucher le plus de joueurs possible en 30 secondes. Les joueurs touchés s'assoient. Après 30 secondes, on arrête et on compte. On recommence avec 2 nouveaux agents secrets que personne ne connaît. L'agent qui touche le plus de joueurs sur l'ensemble des manches gagne.",duree:"10 min",materiel:"Aucun",intensite:"Moyen"},
{cat:"Poursuite",titre:"La Rivière aux Crocodiles",desc:"Tracez une large rivière au centre du gymnase avec des cônes (environ 5 mètres de large). Placez 3-4 crocodiles dans la rivière avec des dossards. Les autres joueurs doivent traverser la rivière sans se faire toucher. Les crocodiles ne peuvent se déplacer que latéralement dans la rivière. Les joueurs touchés deviennent des roches immobiles dans la rivière qui bloquent le passage. Variante : les joueurs peuvent sauter par-dessus les roches.",duree:"12 min",materiel:"Cônes, dossards",intensite:"Élevé"},
{cat:"Poursuite",titre:"Attrape-Foulard Tactique",desc:"Chaque joueur place un foulard dans sa ceinture arrière, bien visible. Au signal, tous les joueurs tentent d'arracher les foulards des autres tout en protégeant le leur. Un joueur qui perd son foulard fait 5 jumping jacks puis récupère un nouveau foulard dans le bac central. Comptez les foulards récoltés après 5 minutes. Le joueur avec le plus de foulards collectés gagne. Variante : par équipes de 4.",duree:"10 min",materiel:"Foulards (1 par élève + extras)",intensite:"Élevé"},
{cat:"Poursuite",titre:"Sardines",desc:"Un seul joueur va se cacher dans le gymnase (derrière l'équipement, sous un tapis, etc.) pendant que tous les autres ferment les yeux et comptent jusqu'à 30. Ensuite, chacun cherche individuellement. Quand un joueur trouve la cachette, il s'y glisse silencieusement sans alerter les autres. Progressivement, tous se retrouvent entassés comme des sardines. Le dernier à trouver la cachette se cache au prochain tour.",duree:"10 min",materiel:"Aucun",intensite:"Faible"},
{cat:"Poursuite",titre:"Le Renard dans le Poulailler",desc:"Délimitez un grand cercle avec des cônes (le poulailler). Tous les joueurs (les poules) sont dans le cercle. Deux renards sont à l'extérieur. Au signal, les renards entrent dans le poulailler et touchent les poules. Les poules touchées sortent du cercle et font 5 squats avant de pouvoir rentrer. Les renards jouent 2 minutes puis on change. Les renards qui touchent le plus de poules gagnent.",duree:"10 min",materiel:"Cônes, dossards",intensite:"Élevé"},
{cat:"Poursuite",titre:"Pacman Géant",desc:"Utilisez les lignes du gymnase comme corridors. Tous les joueurs, y compris le Pacman (dossard jaune) et les 2 fantômes (dossards de couleur), ne peuvent se déplacer QUE sur les lignes. Le Pacman doit ramasser les objets posés aux intersections des lignes sans se faire toucher par les fantômes. Si Pacman est touché, on change les rôles. Le Pacman qui ramasse le plus d'objets gagne.",duree:"12 min",materiel:"Dossards, sacs de fèves",intensite:"Élevé"},
{cat:"Poursuite",titre:"Capture Éclair",desc:"Formez des paires. Dans chaque paire, un joueur est le poursuivant et l'autre le fuyard. Au signal, les fuyards ont 3 secondes d'avance puis les poursuivants partent. Le poursuivant a 20 secondes pour toucher son partenaire. Si le fuyard survit, il marque un point. On inverse les rôles et on recommence. Après 5 manches chacun, le joueur avec le plus de points gagne. Variante : changer de partenaire à chaque manche.",duree:"10 min",materiel:"Chronomètre",intensite:"Élevé"},
{cat:"Poursuite",titre:"La Chasse aux Sorcières",desc:"Désignez 3 sorcières avec des dossards. Les sorcières peuvent transformer les joueurs en statues en les touchant. Un joueur transformé en statue reste immobile, les bras en l'air. Pour être libéré, deux joueurs libres doivent simultanément toucher chacune de ses mains. Les sorcières gagnent si tous les joueurs sont des statues. Les joueurs gagnent s'ils survivent 4 minutes.",duree:"12 min",materiel:"Dossards",intensite:"Élevé"},
{cat:"Poursuite",titre:"Poursuite en Miroir",desc:"Formez des paires face à face sur la ligne centrale. Un côté est désigné attaquant et l'autre défenseur. L'enseignant appelle des consignes (nombre pair = les attaquants poursuivent, impair = les défenseurs poursuivent). Les joueurs doivent réagir instantanément et courir vers leur mur de sécurité. Le joueur touché avant d'atteindre son mur donne un point à l'adversaire. Après 10 manches, le joueur avec le plus de points gagne.",duree:"10 min",materiel:"Aucun",intensite:"Élevé"},
{cat:"Poursuite",titre:"Le Volcan",desc:"Placez un cerceau au centre du gymnase. Un joueur est le volcan et se tient dans le cerceau avec 10 balles en mousse. Les autres joueurs courent autour. Quand l'enseignant crie Éruption, le volcan lance ses balles pour toucher les coureurs. Tout joueur touché s'assoit sur place. Après chaque éruption, le volcan récupère ses balles. Après 3 éruptions, on change de volcan. Le volcan qui élimine le plus de joueurs gagne.",duree:"10 min",materiel:"Balles en mousse, cerceau",intensite:"Élevé"},
// ===== COOPÉRATION (20 jeux) =====
{cat:"Coopération",titre:"La Traversée du Marais",desc:"L'équipe (6-8 joueurs) doit traverser le gymnase sans toucher le sol, en utilisant uniquement 4 tapis comme plateformes. Les joueurs doivent déplacer les tapis devant eux au fur et à mesure. Si un joueur touche le sol, toute l'équipe recommence du début. La première équipe qui atteint le mur opposé sans faute gagne. Variante : réduire le nombre de tapis à 3 pour augmenter le défi.",duree:"12 min",materiel:"Tapis de gymnastique",intensite:"Moyen"},
{cat:"Coopération",titre:"La Tour Infernale",desc:"En équipes de 5, les joueurs doivent construire la plus haute tour possible en empilant des objets variés (cônes, blocs, sacs de fèves) en 3 minutes. Chaque joueur ne peut placer qu'un objet à la fois et doit revenir à la ligne de départ avant qu'un autre coéquipier parte. Si la tour tombe, on recommence à zéro. L'équipe avec la tour la plus haute à la fin du temps gagne.",duree:"10 min",materiel:"Cônes, blocs en mousse, sacs de fèves",intensite:"Faible"},
{cat:"Coopération",titre:"Le Noeud Humain",desc:"En groupes de 8-10, les joueurs se placent en cercle serré, ferment les yeux et avancent les mains pour saisir deux mains différentes (pas celles de leurs voisins immédiats). En ouvrant les yeux, le groupe forme un noeud emmêlé. Sans lâcher les mains, ils doivent communiquer et se démêler pour reformer un cercle. Donnez un maximum de 5 minutes par tentative. Le groupe qui se démêle le plus rapidement gagne.",duree:"10 min",materiel:"Aucun",intensite:"Faible"},
{cat:"Coopération",titre:"Le Radeau de Sauvetage",desc:"Placez un grand tapis au centre du gymnase. Toute la classe doit tenir debout sur le tapis en même temps pendant 10 secondes. Ensuite, pliez le tapis en deux et recommencez. Continuez à réduire la surface. Les élèves doivent s'organiser, se tenir et se soutenir mutuellement. L'objectif est de réussir à tenir sur la plus petite surface possible. Si quelqu'un touche le sol, on recommence cette étape.",duree:"10 min",materiel:"Grand tapis",intensite:"Faible"},
{cat:"Coopération",titre:"Transport de Blessé",desc:"En équipes de 4, les joueurs doivent transporter un coéquipier (le blessé) d'un bout à l'autre du gymnase en utilisant seulement un tapis comme civière. Le blessé doit garder les yeux fermés. Les 3 transporteurs se coordonnent pour un transport sécuritaire et rapide. Si le blessé touche le sol, l'équipe recommence. Chaque joueur est blessé à tour de rôle. L'équipe avec le meilleur temps total gagne.",duree:"15 min",materiel:"Tapis de gymnastique",intensite:"Moyen"},
{cat:"Coopération",titre:"La Chenille Olympique",desc:"En équipes de 6, les joueurs forment une file indienne. Chaque joueur tient les chevilles du joueur devant lui sauf le premier. L'équipe doit se déplacer ensemble du départ à l'arrivée sans se détacher. Si la chaîne se brise, l'équipe s'arrête et se reforme avant de repartir. La première équipe à franchir la ligne d'arrivée au complet gagne. Variante : faire le parcours à reculons ou en contournant des cônes.",duree:"10 min",materiel:"Cônes",intensite:"Moyen"},
{cat:"Coopération",titre:"Le Parachute Stratégique",desc:"Tous les joueurs tiennent le bord du parachute. Placez 3 balles de couleurs différentes dessus. L'équipe doit faire traverser les balles à travers le trou central une à la fois, dans l'ordre annoncé par l'enseignant (ex: rouge, puis bleue, puis jaune). Les joueurs coordonnent leurs mouvements pour diriger chaque balle vers le trou. Si une mauvaise balle tombe en premier, on recommence. L'objectif est de réussir en moins de tentatives possible.",duree:"12 min",materiel:"Parachute, balles de couleurs",intensite:"Moyen"},
{cat:"Coopération",titre:"Le Pont Humain",desc:"L'équipe doit créer un pont humain continu d'un mur à l'autre. Les joueurs se placent en position de planche ou de pont (dos au sol, ventre vers le haut). Un joueur léger marche doucement sur les ponts humains. Quand il passe un joueur, celui-ci court se replacer au bout de la chaîne. Toute l'équipe doit traverser le gymnase de cette façon. Chronométrez et tentez de battre le record de la classe.",duree:"15 min",materiel:"Tapis de gymnastique",intensite:"Élevé"},
{cat:"Coopération",titre:"Désamorçage de Bombe",desc:"Placez un chronomètre visible au centre du gymnase. L'équipe a exactement 3 minutes pour compléter 5 défis physiques dans l'ordre : faire 50 sauts groupés collectifs, transporter 10 balles une par une dans un cerceau éloigné, faire une pyramide humaine, que tous réussissent un lancer dans un panier, et former les lettres BOMBE avec leurs corps au sol. Si le temps expire, toute l'équipe fait 10 burpees.",duree:"12 min",materiel:"Chronomètre, balles, cerceau, panier",intensite:"Élevé"},
{cat:"Coopération",titre:"L'Architecte Aveugle",desc:"En paires, un joueur est l'architecte (il voit) et l'autre est le constructeur (yeux bandés). L'architecte donne des instructions verbales pour que le constructeur place des cônes, cerceaux et blocs dans un arrangement spécifique montré sur une image. L'architecte ne peut pas toucher le matériel. L'équipe a 3 minutes pour reproduire le modèle. Comparez le résultat avec l'image originale. Inversez les rôles ensuite.",duree:"12 min",materiel:"Cônes, cerceaux, blocs, bandeaux, images modèles",intensite:"Faible"},
{cat:"Coopération",titre:"Le Tapis Volant",desc:"En équipes de 6, tous les joueurs se tiennent debout sur un grand tapis. Le défi : retourner le tapis à l'envers sans qu'aucun joueur ne touche le sol. Les joueurs doivent se déplacer et s'organiser pour plier et retourner le tapis sous leurs pieds. Si un joueur touche le sol, on recommence. L'équipe qui retourne son tapis le plus rapidement gagne. Variante : interdire la parole, communiquer seulement par gestes.",duree:"10 min",materiel:"Grand tapis",intensite:"Moyen"},
{cat:"Coopération",titre:"Le Pipeline",desc:"En équipes de 8, chaque joueur reçoit un demi-tuyau (frite de piscine coupée en deux dans le sens de la longueur). L'équipe doit transporter une balle de tennis du point A au point B en la faisant rouler de tuyau en tuyau sans qu'elle tombe. Quand la balle a quitté son tuyau, le joueur court se replacer au bout de la chaîne. Si la balle tombe, on recommence du début. L'équipe qui parcourt la plus grande distance en 5 minutes gagne.",duree:"12 min",materiel:"Frites de piscine coupées, balles de tennis",intensite:"Moyen"},
{cat:"Coopération",titre:"Le Cercle de Confiance",desc:"En groupes de 8, les joueurs forment un cercle serré. Un joueur se place au centre, ferme les yeux, garde le corps rigide et se laisse tomber doucement dans n'importe quelle direction. Les joueurs du cercle le rattrapent et le repoussent doucement vers le centre. Chaque joueur passe au centre pendant 30 secondes. Insistez sur la sécurité et le respect. Variante : agrandir progressivement le cercle.",duree:"10 min",materiel:"Aucun",intensite:"Faible"},
{cat:"Coopération",titre:"Le Record du Monde",desc:"La classe tente de battre des records collectifs chronométrés. Exemples : tout le monde complète un tour de gymnase en se tenant par les mains sans se lâcher, lancer et rattraper un ballon 50 fois de suite sans le faire tomber en cercle, ou faire une vague mexicaine parfaite en moins de 5 secondes. Notez les records au tableau et tentez de les battre à chaque manche.",duree:"12 min",materiel:"Ballon, chronomètre",intensite:"Moyen"},
{cat:"Coopération",titre:"Le Convoi Humanitaire",desc:"En équipes de 6, les joueurs doivent transporter 15 objets variés d'un bout du gymnase à l'autre. Chaque joueur ne peut utiliser qu'une seule main et ne peut transporter qu'un objet à la fois. De plus, les joueurs doivent se passer les objets en chaîne sans marcher (un seul joueur à la fois peut se déplacer). L'équipe qui transporte tous ses objets en premier gagne.",duree:"12 min",materiel:"Balles, sacs de fèves, cônes",intensite:"Moyen"},
{cat:"Coopération",titre:"L'Évasion de la Salle",desc:"Toute la classe forme un seul grand groupe. Placez 5 défis dans le gymnase que l'équipe doit résoudre en séquence : passer tout le monde par-dessus un banc sans le toucher, former un mot avec les corps, empiler 10 cônes en pyramide les yeux bandés, faire traverser un ballon du premier au dernier sans utiliser les mains, et que tous sautent en même temps. Temps limite : 10 minutes.",duree:"15 min",materiel:"Banc, cônes, ballon, bandeau, cerceaux",intensite:"Moyen"},
{cat:"Coopération",titre:"Le Transporteur de Billes",desc:"En équipes de 4, les joueurs tiennent chacun une corde attachée à un plateau central. Ils doivent transporter une balle de tennis posée sur le plateau sur un parcours de cônes sans la faire tomber. Les 4 joueurs coordonnent leur tension sur les cordes et leur vitesse de marche. Si la balle tombe, on recommence au dernier point de contrôle. L'équipe avec le meilleur temps gagne.",duree:"12 min",materiel:"Plateau, cordes, balle de tennis, cônes",intensite:"Faible"},
{cat:"Coopération",titre:"Les Engrenages Humains",desc:"En groupes de 10, les joueurs créent une machine humaine. Le premier joueur fait un mouvement répétitif simple. Le deuxième se connecte et ajoute un mouvement lié au premier. Continuez jusqu'à ce que les 10 joueurs forment une machine complète qui bouge de façon synchronisée. L'enseignant peut accélérer ou ralentir la machine. Le groupe qui crée la machine la plus fluide et originale gagne. Variante : ajouter des effets sonores.",duree:"10 min",materiel:"Aucun",intensite:"Faible"},
{cat:"Coopération",titre:"Le Filet de Pêche",desc:"Deux joueurs se tiennent par la main et forment le filet. Ils poursuivent les poissons (tous les autres joueurs). Quand un poisson est touché, il s'ajoute au filet en prenant la main d'un joueur du bout. Le filet grandit à chaque capture et doit rester intact. Quand le filet atteint 6 joueurs, il se divise en deux filets de 3. Le jeu se termine quand tous les poissons sont capturés.",duree:"12 min",materiel:"Aucun",intensite:"Élevé"},
{cat:"Coopération",titre:"Sauvetage en Montagne",desc:"Divisez le gymnase en zones : base (départ), sentier (parcours d'obstacles avec bancs et cônes), sommet (un tapis éloigné) et hôpital (cerceau). En équipes de 5, un blessé se trouve au sommet. L'équipe doit naviguer le sentier, atteindre le blessé et le transporter sur un tapis-civière à travers le parcours. Si un joueur touche un obstacle, l'équipe recule de 3 pas. Meilleur temps gagne.",duree:"15 min",materiel:"Tapis, bancs, cônes, cerceaux",intensite:"Moyen"},
// ===== BALLON CHASSEUR (20 jeux) =====
{cat:"Ballon chasseur",titre:"Ballon Chasseur Classique Avancé",desc:"Divisez la classe en deux équipes, chacune dans sa moitié de gymnase. Placez 4-6 ballons en mousse sur la ligne centrale. Au signal, les joueurs lancent les ballons pour toucher les adversaires sous les épaules. Un joueur touché s'assoit sur place et peut se relever s'il attrape un ballon roulant ou si un coéquipier l'atteint. Si un joueur attrape un ballon en vol, le lanceur est éliminé. L'équipe qui élimine tous les adversaires gagne.",duree:"12 min",materiel:"Ballons en mousse",intensite:"Élevé"},
{cat:"Ballon chasseur",titre:"Chasseur Royal",desc:"Même principe que le ballon chasseur classique, mais chaque équipe a un roi secret que personne ne connaît sauf l'enseignant. Le roi porte un signe discret (bracelet). Si le roi est touché, toute son équipe est éliminée immédiatement. Les coéquipiers doivent protéger leur roi sans révéler son identité. Le jeu se termine quand un roi est touché ou quand une équipe est complètement éliminée.",duree:"12 min",materiel:"Ballons en mousse, bracelets",intensite:"Élevé"},
{cat:"Ballon chasseur",titre:"Chasseur Médecin",desc:"Chaque équipe désigne secrètement un médecin. Le jeu se déroule comme un ballon chasseur normal, mais quand un joueur est touché, il s'assoit sur place. Le médecin peut ramper jusqu'aux joueurs assis et les toucher pour les ressusciter. Si le médecin est touché, plus de guérison possible pour l'équipe. L'équipe adverse doit deviner qui est le médecin et le cibler. Dernière équipe debout gagne.",duree:"12 min",materiel:"Ballons en mousse",intensite:"Élevé"},
{cat:"Ballon chasseur",titre:"Bombardement",desc:"Chaque équipe a une quille placée au fond de son terrain. Les joueurs doivent protéger leur quille tout en essayant de renverser celle de l'adversaire avec des ballons en mousse. Les joueurs touchés s'assoient 15 secondes puis reviennent. On ne peut pas toucher sa propre quille (zone interdite d'un mètre autour). L'équipe qui renverse la quille adverse gagne. Variante : 3 quilles par équipe.",duree:"12 min",materiel:"Ballons en mousse, quilles ou bouteilles",intensite:"Élevé"},
{cat:"Ballon chasseur",titre:"Chasseur Prisonnier",desc:"Divisez le gymnase en 4 zones : deux terrains principaux et deux prisons derrière chaque terrain adverse. Les joueurs touchés vont en prison. Un prisonnier peut être libéré si un coéquipier lui envoie un ballon qu'il attrape en vol. Le prisonnier libéré revient sur son terrain avec le ballon. L'équipe qui envoie tous les adversaires en prison gagne. Les prisonniers peuvent aussi toucher les adversaires depuis la prison.",duree:"15 min",materiel:"Ballons en mousse",intensite:"Élevé"},
{cat:"Ballon chasseur",titre:"Chasseur Évolutif",desc:"Commencez avec une seule balle en mousse et deux équipes. Toutes les 2 minutes, ajoutez un nouveau ballon dans le jeu jusqu'à 6 ballons. Les règles de base s'appliquent. Les joueurs éliminés font des exercices en bordure et reviennent quand un nouveau ballon est ajouté. L'équipe avec le plus de joueurs debout à la fin gagne.",duree:"15 min",materiel:"6 ballons en mousse",intensite:"Élevé"},
{cat:"Ballon chasseur",titre:"Chasseur à Rebonds",desc:"Même règles que le ballon chasseur classique, sauf qu'un ballon qui touche un joueur APRÈS avoir rebondi au sol ne compte pas. Seuls les lancers directs éliminent. Un joueur peut récupérer un ballon ayant rebondi et le relancer immédiatement. Les joueurs éliminés s'alignent en bordure et reviennent si un coéquipier attrape un ballon en vol. Dernière équipe debout gagne.",duree:"12 min",materiel:"Ballons en mousse",intensite:"Élevé"},
{cat:"Ballon chasseur",titre:"Chasseur Zombies",desc:"Une équipe est les humains, l'autre les zombies. Les humains ont tous les ballons et doivent toucher les zombies pour les éliminer. Les zombies n'ont pas de ballons et avancent lentement vers les humains. Un zombie touché s'assoit 10 secondes puis se relève. Si un zombie touche un humain avec sa main, l'humain devient zombie. Le jeu se termine quand tous sont zombies ou après 5 minutes.",duree:"12 min",materiel:"Ballons en mousse, dossards",intensite:"Élevé"},
{cat:"Ballon chasseur",titre:"Chasseur Bouclier",desc:"Ballon chasseur classique avec un ajout : chaque équipe possède 2 boucliers (tapis de mousse légers). Les porteurs de bouclier peuvent bloquer les tirs pour protéger leurs coéquipiers mais ne peuvent pas lancer. Le porteur peut être éliminé s'il est touché dans le dos. Quand un porteur est éliminé, il passe son bouclier à un coéquipier. L'équipe sans joueurs debout perd.",duree:"12 min",materiel:"Ballons en mousse, tapis mousse légers",intensite:"Élevé"},
{cat:"Ballon chasseur",titre:"Chasseur 4 Coins",desc:"Divisez le gymnase en 4 zones égales. Formez 4 équipes, chacune dans un coin. Placez des ballons au centre. Au signal, chaque équipe peut viser n'importe quelle autre équipe. Les joueurs touchés s'assoient mais peuvent se relever si leur équipe attrape un ballon en vol. L'équipe entièrement éliminée donne ses ballons aux équipes restantes. La dernière équipe avec au moins un joueur debout gagne.",duree:"12 min",materiel:"Ballons en mousse, cônes",intensite:"Élevé"},
{cat:"Ballon chasseur",titre:"Chasseur Silencieux",desc:"Même principe que le ballon chasseur classique, mais AUCUN joueur n'a le droit de parler. Tout son (cri, mot, rire fort) entraîne l'élimination immédiate du joueur bruyant. Les joueurs communiquent uniquement par gestes et regards. Cela ajoute un défi de self-control et de communication non-verbale. L'équipe qui élimine tous les adversaires ou qui a le plus de joueurs après 5 minutes gagne.",duree:"10 min",materiel:"Ballons en mousse",intensite:"Moyen"},
{cat:"Ballon chasseur",titre:"Chasseur Base Protégée",desc:"Chaque équipe a 3 cerceaux contenant un objet chacun. Le but est de voler les objets adverses tout en jouant au ballon chasseur. Un joueur peut traverser en territoire adverse pour voler un objet, mais s'il est touché il retourne les mains vides. Les lanceurs restent de leur côté. L'équipe qui vole les 3 objets adverses ou élimine tout le monde gagne.",duree:"15 min",materiel:"Ballons en mousse, cerceaux, sacs de fèves",intensite:"Élevé"},
{cat:"Ballon chasseur",titre:"Chasseur Compte à Rebours",desc:"Ballon chasseur classique, mais un joueur qui tient un ballon a seulement 5 secondes pour le lancer (la classe compte à voix haute). S'il dépasse 5 secondes, il est éliminé. Cela empêche les joueurs de garder le ballon et accélère le rythme. Les joueurs éliminés font des exercices en bordure et reviennent au jeu à chaque minute écoulée.",duree:"12 min",materiel:"Ballons en mousse",intensite:"Élevé"},
{cat:"Ballon chasseur",titre:"Chasseur Protecteur",desc:"Chaque joueur se voit attribuer secrètement un joueur de l'autre équipe à protéger (cartons avec les noms). Pendant le jeu normal, chaque joueur essaie de bloquer les tirs dirigés vers la personne qu'il protège. Personne ne sait qui le protège. Après la partie, on révèle les protecteurs. Cela ajoute une dimension stratégique et altruiste au jeu.",duree:"12 min",materiel:"Ballons en mousse, cartons avec noms",intensite:"Élevé"},
{cat:"Ballon chasseur",titre:"Chasseur Décroissant",desc:"Commencez avec le gymnase complet. Toutes les 90 secondes, l'enseignant réduit la zone de jeu en avançant une ligne de cônes. Le terrain rétrécit progressivement, rendant l'esquive de plus en plus difficile. Les joueurs touchés sont éliminés définitivement. Les joueurs sortant de la zone sont aussi éliminés. Le dernier joueur debout gagne.",duree:"12 min",materiel:"Ballons en mousse, cônes",intensite:"Élevé"},
{cat:"Ballon chasseur",titre:"Chasseur Alliances",desc:"Commencez avec 4 équipes de 5-6 joueurs. Chaque équipe joue pour elle-même. Après 2 minutes, l'enseignant permet aux équipes de former des alliances temporaires (2 équipes alliées ne se visent pas pendant 1 minute). Les alliances changent à chaque signal. Les joueurs éliminés reviennent au prochain changement d'alliance. L'équipe avec le plus de joueurs debout à la fin gagne.",duree:"15 min",materiel:"Ballons en mousse, dossards 4 couleurs",intensite:"Élevé"},
{cat:"Ballon chasseur",titre:"Chasseur Aveugle",desc:"Un joueur par équipe est le tireur aveugle (yeux bandés) positionné à l'avant de son territoire. Ses coéquipiers lui donnent des directives vocales pour qu'il touche les adversaires. Seuls les tirs du tireur aveugle comptent pour des éliminations. Les autres joueurs récupèrent les ballons et les redonnent au tireur. Changez de tireur aveugle toutes les 2 minutes.",duree:"12 min",materiel:"Ballons en mousse, bandeau",intensite:"Moyen"},
{cat:"Ballon chasseur",titre:"Chasseur Forteresse",desc:"Chaque équipe construit une forteresse avec des tapis, bancs et cônes. Les joueurs peuvent se cacher derrière pour esquiver les tirs. Le but est de détruire la forteresse adverse en la touchant avec des ballons (chaque impact enlève un élément). Les joueurs touchés directement s'assoient 20 secondes puis reviennent. L'équipe dont la forteresse est complètement démolie en premier perd.",duree:"15 min",materiel:"Ballons en mousse, tapis, bancs, cônes",intensite:"Élevé"},
// ===== SPORT COLLECTIF (20 jeux) =====
{cat:"Sport collectif",titre:"Basketball Modifié",desc:"Deux équipes de 5-6 joueurs s'affrontent avec des paniers ou cerceaux tenus en hauteur. Le porteur du ballon ne peut pas se déplacer et doit passer à un coéquipier en 5 secondes maximum. Le ballon ne peut pas être arraché des mains. Un panier réussi vaut 2 points. Après chaque panier, l'autre équipe repart du centre. L'équipe avec le plus de points après 10 minutes gagne.",duree:"15 min",materiel:"Ballon de basketball ou mousse, cônes",intensite:"Élevé"},
{cat:"Sport collectif",titre:"Handball Simplifié",desc:"Deux équipes sur tout le gymnase avec un but à chaque extrémité (2 cônes espacés de 2 mètres). Les joueurs se passent un ballon en mousse et tentent de marquer en lançant entre les cônes. Le gardien protège son but. Le porteur a 3 pas maximum puis doit passer ou lancer. Pas de contact physique. Un but vaut 1 point. L'équipe avec le plus de buts après 10 minutes gagne.",duree:"15 min",materiel:"Ballon en mousse, cônes",intensite:"Élevé"},
{cat:"Sport collectif",titre:"Ultimate Frisbee",desc:"Deux équipes s'affrontent sur le gymnase entier. Chaque bout est une zone des buts. Les joueurs se passent le frisbee pour atteindre la zone adverse. Le porteur ne peut pas se déplacer et a 10 secondes pour lancer. Si le frisbee tombe ou est intercepté, l'autre équipe le récupère. Un point quand un joueur attrape le frisbee dans la zone des buts adverse. L'équipe à 5 points gagne.",duree:"15 min",materiel:"Frisbee, cônes",intensite:"Élevé"},
{cat:"Sport collectif",titre:"Soccer Intérieur Modifié",desc:"Deux équipes jouent au soccer avec un ballon en mousse. Les buts sont délimités par des cônes de 2 mètres de large. Règles spéciales : pas de tir au-dessus de la taille, pas de gardien fixe, et changement de possession après chaque but. Les touches de main sont permises pour arrêter un ballon haut dangereux. L'équipe avec le plus de buts après 10 minutes gagne.",duree:"15 min",materiel:"Ballon en mousse, cônes",intensite:"Élevé"},
{cat:"Sport collectif",titre:"Tchoukball",desc:"Deux équipes de 6 partagent le terrain avec deux cadres de rebond aux extrémités. Les joueurs se passent le ballon (3 passes max) puis lancent sur le cadre. Le ballon rebondit et l'équipe adverse doit l'attraper avant qu'il touche le sol. Si le ballon touche le sol après le rebond, l'équipe lanceuse marque un point. Si l'adversaire l'attrape, il récupère la possession. Aucun contact permis.",duree:"15 min",materiel:"Ballon, cadre de rebond ou trampoline incliné",intensite:"Élevé"},
{cat:"Sport collectif",titre:"Kin-Ball",desc:"Trois équipes de 4 joueurs avec un gros ballon. L'équipe en possession frappe le ballon en criant le nom de couleur d'une équipe adverse. Cette équipe doit attraper le ballon avant qu'il touche le sol. Si le ballon touche le sol, les deux autres équipes marquent un point. L'équipe nommée récupère la possession. Première équipe à 10 points gagne.",duree:"15 min",materiel:"Gros ballon ou ballon de plage, dossards 3 couleurs",intensite:"Moyen"},
{cat:"Sport collectif",titre:"Flag-Football",desc:"Deux équipes de 6-8. Chaque joueur porte un foulard à la ceinture. L'équipe en attaque a 4 tentatives pour traverser le terrain et marquer dans la zone adverse. Les défenseurs arrachent le foulard du porteur pour arrêter le jeu. Pas de contact physique. L'attaque avance du point où le foulard a été arraché. Après 4 tentatives ou un touché, les équipes changent de rôle.",duree:"15 min",materiel:"Ballon en mousse, foulards",intensite:"Élevé"},
{cat:"Sport collectif",titre:"Hockey Cosom",desc:"Deux équipes de 6 avec des bâtons cosom et une balle légère. Les buts sont délimités par des cônes. Règle de sécurité : le bâton ne doit jamais dépasser la hauteur des genoux. Pas de tir frappé, seulement des tirs du poignet. Après chaque but, remise au jeu au centre. L'équipe avec le plus de buts en 10 minutes gagne.",duree:"15 min",materiel:"Bâtons cosom, balle ou rondelle mousse, cônes",intensite:"Élevé"},
{cat:"Sport collectif",titre:"Volleyball Coopératif",desc:"Deux équipes séparées par un filet ou une corde. Le ballon doit être touché par au moins 3 joueurs différents avant de passer de l'autre côté. Les joueurs peuvent attraper et relancer le ballon. Si le ballon touche le sol, l'autre équipe marque. Rotation des positions après chaque 3 points. L'équipe à 15 points gagne. Variante : utiliser un ballon de plage pour ralentir le jeu.",duree:"15 min",materiel:"Ballon de plage ou volleyball léger, filet ou corde",intensite:"Moyen"},
{cat:"Sport collectif",titre:"Balle aux Murs",desc:"Deux équipes occupent chacune une moitié du gymnase. Le but est de lancer le ballon pour qu'il touche le mur derrière l'équipe adverse. Les joueurs se passent le ballon et le lancent vers le mur. Les défenseurs tentent de bloquer ou attraper. Le porteur a 3 secondes pour passer ou lancer. Chaque touche du mur adverse vaut un point. Première équipe à 10 points gagne.",duree:"12 min",materiel:"Ballon en mousse",intensite:"Élevé"},
{cat:"Sport collectif",titre:"Quidditch au Sol",desc:"Deux équipes de 7. Les poursuiveurs (4) se passent un ballon et tentent de marquer dans des cerceaux tenus en hauteur. Les batteurs (2) lancent des balles en mousse pour geler les adversaires pendant 10 secondes. L'attrapeur (1) cherche un petit objet caché par l'enseignant. Un but = 10 points, attraper le vif d'or = 30 points et fin de manche.",duree:"15 min",materiel:"Ballons, balles en mousse, cerceaux, petit objet",intensite:"Élevé"},
{cat:"Sport collectif",titre:"Poull Ball",desc:"Deux équipes de 6-8 joueurs avec un gros ballon. Deux zones de but à chaque extrémité contiennent un gros cube ou matelas vertical. Les joueurs se passent le ballon et doivent le lancer pour toucher le cube adverse. Le porteur ne peut pas marcher et a 5 secondes pour jouer. Aucun contact permis. Chaque touche du cube vaut 1 point. L'équipe à 10 points gagne.",duree:"15 min",materiel:"Gros ballon, cube ou matelas, cônes",intensite:"Moyen"},
{cat:"Sport collectif",titre:"Balle au Capitaine",desc:"Deux équipes de 6-8 joueurs. Chaque équipe désigne un capitaine qui se place debout sur un banc au bout du terrain adverse. Les joueurs tentent de lancer le ballon au capitaine qui doit l'attraper en restant sur le banc. Le porteur ne peut pas se déplacer (3 secondes pour passer). Pas d'interception au-dessus du capitaine. Changez de capitaine tous les 3 points. Première équipe à 10 points.",duree:"12 min",materiel:"Ballon en mousse, bancs",intensite:"Élevé"},
{cat:"Sport collectif",titre:"Rugby Tag",desc:"Deux équipes de 6-8. Chaque joueur porte 2 foulards à la ceinture. Le porteur du ballon avance vers la zone d'essai adverse. Les défenseurs retirent un foulard pour arrêter le jeu. Les passes ne vont que vers l'arrière comme au rugby. Après 5 retraits de foulards, l'équipe perd la possession. Un essai dans la zone vaut 5 points.",duree:"15 min",materiel:"Ballon en mousse, foulards",intensite:"Élevé"},
{cat:"Sport collectif",titre:"Basket-Cerceau",desc:"Comme le basketball, mais au lieu de paniers, placez 3 cerceaux au sol dans chaque zone de but. Un receveur de chaque équipe se place derrière les cerceaux adverses. Pour marquer, le ballon doit être attrapé par le receveur dans un cerceau. Chaque cerceau ne peut être utilisé qu'une fois par manche. Quand les 3 cerceaux sont marqués, l'équipe gagne la manche.",duree:"15 min",materiel:"Ballon, cerceaux, cônes",intensite:"Élevé"},
{cat:"Sport collectif",titre:"Ringette Simplifiée",desc:"Deux équipes de 6 avec des bâtons de ringette et un anneau en caoutchouc. Les joueurs passent l'anneau en le piquant avec le bâton et en le lançant. Le but est de faire pénétrer l'anneau entre 2 cônes. Le bâton ne doit pas dépasser la taille. Pas de contact entre les bâtons. Après chaque but, remise au centre. L'équipe avec le plus de buts en 10 minutes gagne.",duree:"15 min",materiel:"Bâtons, anneau, cônes",intensite:"Élevé"},
{cat:"Sport collectif",titre:"Ballon Prisonnier Sportif",desc:"Deux équipes de 8. Le terrain est divisé en deux moitiés avec une zone de prison derrière chaque camp adverse. Si le ballon touche le sol dans votre camp, un de vos joueurs va en prison. Les prisonniers peuvent être libérés s'ils attrapent un ballon lancé par leurs coéquipiers. L'équipe qui met tous les adversaires en prison gagne.",duree:"15 min",materiel:"Ballon en mousse",intensite:"Élevé"},
{cat:"Sport collectif",titre:"Bumball",desc:"Les joueurs portent des dossards avec du velcro. Le ballon (recouvert de velcro) colle aux dossards quand il touche un joueur. Pour passer, un joueur doit décoller le ballon et le lancer à un coéquipier. Le porteur ne peut pas courir avec le ballon collé. Pour marquer, le ballon doit coller au dossard d'un joueur dans la zone des buts adverse. Premier à 5 buts gagne.",duree:"12 min",materiel:"Dossards velcro, ballon velcro",intensite:"Élevé"},
{cat:"Sport collectif",titre:"Spikeball Géant",desc:"Adaptez le spikeball pour le gymnase. Placez un trampoline ou un filet au centre. Deux équipes de 3. L'équipe en possession a 3 touches pour renvoyer le ballon sur le filet. L'autre équipe doit récupérer le rebond en maximum 3 touches. Si le ballon touche le sol, l'autre équipe marque. Jouez à 15 points. Variante : permettre 4 touches pour les débutants.",duree:"12 min",materiel:"Ballon, filet ou trampoline",intensite:"Élevé"},
// ===== MANIPULATION (20 jeux) =====
{cat:"Manipulation",titre:"Jonglerie Progressive",desc:"Chaque joueur reçoit un foulard léger. Commencez par lancer et rattraper un foulard d'une main. Ajoutez un deuxième foulard puis tentez 3 foulards en cascade. Passez ensuite aux balles de tennis : une balle d'une main à l'autre, puis deux balles. Donnez 10 minutes de pratique libre puis organisez un petit spectacle par équipes.",duree:"15 min",materiel:"Foulards légers, balles de tennis",intensite:"Faible"},
{cat:"Manipulation",titre:"Lancer de Précision Olympique",desc:"Installez 5 stations de lancer : station 1 — sac de fèves dans un cerceau à 3m; station 2 — balle dans un seau à 4m; station 3 — renverser des quilles avec un ballon; station 4 — frisbee entre deux cônes; station 5 — balle sur une cible murale. Chaque joueur fait 3 essais par station et note ses réussites. Le meilleur score total sur les 5 stations gagne le titre olympique.",duree:"15 min",materiel:"Sacs de fèves, balles, cerceaux, seaux, quilles, frisbees, cônes",intensite:"Moyen"},
{cat:"Manipulation",titre:"Défi Dribble",desc:"Chaque joueur a un ballon. L'enseignant appelle des défis progressifs : dribbler de la main droite seulement, de la gauche, en alternance, en marchant, en courant, en reculant, entre les jambes, autour du corps, les yeux fermés, en s'assoyant puis en se relevant. Chaque défi dure 30 secondes. Les joueurs qui perdent le contrôle font 3 jumping jacks puis reprennent. Dernier défi : dribbler deux ballons simultanément.",duree:"12 min",materiel:"Ballons de basketball ou mousse",intensite:"Moyen"},
{cat:"Manipulation",titre:"Le Cirque des Habiles",desc:"Créez 6 stations circulaires : faire tourner un ballon sur le doigt, équilibre d'un bâton sur la paume, faire tourner un cerceau autour de la taille, lancer et rattraper un sac de fèves derrière le dos, rebondir une balle au sol et la rattraper après un tour complet, jongler deux balles. Les joueurs passent 2 minutes par station et essaient de maîtriser chaque habileté.",duree:"15 min",materiel:"Ballons, bâtons, cerceaux, sacs de fèves, balles de tennis",intensite:"Faible"},
{cat:"Manipulation",titre:"Hockey sur Table Géant",desc:"En équipes de 3, les joueurs sont placés en rangées fixes comme un baby-foot et tiennent un bâton cosom. Ils ne peuvent se déplacer que latéralement sur leur ligne. L'objectif est de passer la balle d'une rangée à l'autre pour marquer dans le but adverse. Cela force la précision des passes et le positionnement stratégique. Un but = 1 point. Première équipe à 5 points gagne.",duree:"12 min",materiel:"Bâtons cosom, balle légère, cônes",intensite:"Moyen"},
{cat:"Manipulation",titre:"Frisbee Golf",desc:"Installez un parcours de 9 trous dans le gymnase. Chaque trou est un cerceau ou une cible à atteindre avec un frisbee. Les joueurs partent d'un point de départ et lancent le frisbee pour atteindre la cible en le moins de lancers possible. Notez le nombre de lancers par trou comme au golf. Le joueur avec le score total le plus bas gagne. Variante : jouer en paires et compter le meilleur lancer.",duree:"15 min",materiel:"Frisbees, cerceaux, cônes, seaux",intensite:"Faible"},
{cat:"Manipulation",titre:"Le Passeur Ninja",desc:"En cercle de 8-10 joueurs, passez le ballon le plus rapidement possible. L'enseignant appelle des variations : passe par terre, passe en cloche, passe derrière le dos, passe entre les jambes, passe avec le pied, passe les yeux fermés. Chronométrez le temps pour un tour complet. Tentez de battre le record à chaque tour. Si le ballon tombe, ajoutez 3 secondes. Le cercle avec le meilleur temps gagne.",duree:"10 min",materiel:"Ballons",intensite:"Moyen"},
{cat:"Manipulation",titre:"Bataille de Raquettes",desc:"Chaque joueur a une raquette de badminton et un volant. Commencez par jongler le volant vers le haut. Puis en paires, échangez par-dessus une ligne de cônes. Augmentez la distance progressivement. Ensuite, mini-tournoi en simple : terrain délimité par 4 cônes, service par en-dessous, point quand le volant touche le sol dans le terrain adverse. Matchs de 5 points puis changement d'adversaire.",duree:"15 min",materiel:"Raquettes de badminton, volants, cônes",intensite:"Moyen"},
{cat:"Manipulation",titre:"Le Relais Manipulation",desc:"En équipes de 5, placez 5 stations en ligne. Station 1 : dribbler un ballon sur 5m. Station 2 : lancer un sac de fèves dans un cerceau. Station 3 : faire 10 rebonds d'une balle avec une raquette. Station 4 : transporter une balle sur une raquette sur 5m. Station 5 : lancer un frisbee dans un cerceau. Le joueur doit réussir chaque station avant de passer à la suivante.",duree:"12 min",materiel:"Ballons, sacs de fèves, cerceaux, balles, raquettes, frisbees",intensite:"Élevé"},
{cat:"Manipulation",titre:"Tir au But Progressif",desc:"Placez 5 lignes de tir à distances croissantes (2m, 3m, 4m, 5m, 6m) face à un but. Chaque joueur a 3 tirs par distance. Un but de la ligne 1 = 1 point, ligne 2 = 2 points, et ainsi de suite. Les joueurs additionnent leurs points. Le joueur ou l'équipe avec le plus de points gagne. Variante : utiliser le pied ou alterner main droite et main gauche.",duree:"12 min",materiel:"Ballons en mousse, cônes",intensite:"Moyen"},
{cat:"Manipulation",titre:"Le Béret Évolutif",desc:"Deux équipes face à face, chaque joueur a un numéro. L'enseignant place un sac de fèves au centre et appelle un numéro. Les deux joueurs correspondants courent pour saisir l'objet et le ramener dans leur camp sans se faire toucher par l'adversaire. Variante évolutive : appeler 2 numéros en même temps pour jouer en paire.",duree:"12 min",materiel:"Sac de fèves, dossards numérotés",intensite:"Élevé"},
{cat:"Manipulation",titre:"Balle Brûlante",desc:"Les joueurs forment un grand cercle et se passent un ballon rapidement pendant que la musique joue. Quand la musique s'arrête, le joueur qui tient le ballon fait un défi physique puis rejoint le cercle. Ajoutez un deuxième puis un troisième ballon pour augmenter l'intensité. Les passes doivent être contrôlées. Le dernier joueur jamais éliminé gagne.",duree:"10 min",materiel:"Ballons, musique",intensite:"Moyen"},
{cat:"Manipulation",titre:"Cible Mouvante",desc:"Suspendez un cerceau au centre du gymnase ou demandez à un joueur de le tenir en bougeant. Les joueurs lancent des sacs de fèves à travers le cerceau en mouvement. Chaque passage vaut 1 point. Chronométrez 3 minutes et comptez les points par équipe. Variante : augmenter la distance de lancer ou réduire la taille du cerceau.",duree:"10 min",materiel:"Cerceau, sacs de fèves, corde",intensite:"Moyen"},
{cat:"Manipulation",titre:"Le Bowling Humain",desc:"Placez 10 quilles en formation de bowling au bout du gymnase. Les joueurs lancent un ballon de la ligne de lancer pour renverser les quilles. Chaque joueur a 2 essais par tour. Comptez le nombre de quilles renversées. Après chaque tour, un joueur replace les quilles. Jouez 5 tours et additionnez les scores. Le joueur ou l'équipe avec le meilleur score gagne.",duree:"15 min",materiel:"Quilles ou bouteilles, ballons",intensite:"Faible"},
{cat:"Manipulation",titre:"Passe et Court",desc:"En équipes de 5, les joueurs se placent en ligne espacés de 3 mètres. Le premier passe le ballon au deuxième puis court se placer au bout de la ligne. Le deuxième passe au troisième et court au bout. L'équipe avance ainsi à travers le gymnase. Si le ballon tombe, l'équipe s'arrête et recommence la passe. La première équipe à traverser 2 fois gagne. Variante : utiliser les pieds.",duree:"10 min",materiel:"Ballons",intensite:"Élevé"},
{cat:"Manipulation",titre:"Le Golf Miniature",desc:"Créez un parcours de 6 trous avec des obstacles. Chaque trou a un départ, un parcours (contourner des cônes, passer sous un banc, longer un mur) et une arrivée (cerceau). Les joueurs utilisent un bâton cosom pour pousser une balle dans le parcours. Comptez les coups par trou. Le joueur avec le score le plus bas gagne. Variante : jouer en paires.",duree:"15 min",materiel:"Bâtons cosom, balles, cônes, cerceaux, bancs",intensite:"Faible"},
{cat:"Manipulation",titre:"Le Jongleur de Cerceaux",desc:"Chaque joueur reçoit un cerceau. Commencez par le faire tourner autour de la taille, puis du bras, puis du cou. Essayez de le lancer et le rattraper. En paires, lancez le cerceau à votre partenaire qui le rattrape en le faisant tourner sur son bras. Défi avancé : faire rouler le cerceau au sol vers un partenaire à 5 mètres. Organisez un concours du meilleur trick par équipes.",duree:"10 min",materiel:"Cerceaux",intensite:"Faible"},
{cat:"Manipulation",titre:"La Balle au Mur Rebond",desc:"En paires face à un mur, un joueur lance la balle de tennis contre le mur et l'autre doit la rattraper après un seul rebond au sol. Commencez proche du mur puis reculez progressivement. Comptez les échanges réussis consécutifs. Quand la paire atteint 10 échanges, elle recule d'un pas. Variante : lancer avec la main non dominante. La paire avec le plus d'échanges gagne.",duree:"10 min",materiel:"Balles de tennis",intensite:"Moyen"},
{cat:"Manipulation",titre:"Le Défi 360",desc:"Chaque joueur a un ballon. L'enseignant appelle des défis progressifs : lancer le ballon et faire un tour complet sur soi-même avant de le rattraper, lancer et taper des mains 3 fois, lancer et toucher le sol, lancer et s'asseoir puis se relever, lancer très haut et rattraper les yeux fermés. Chaque défi réussi vaut un point. Après 10 défis, le meilleur score gagne.",duree:"10 min",materiel:"Ballons",intensite:"Moyen"},
{cat:"Manipulation",titre:"Pétanque Gymnase",desc:"Placez un petit objet coloré (le cochonnet) au centre du gymnase. Les joueurs lancent un sac de fèves chacun pour s'approcher le plus possible du cochonnet. Le joueur le plus éloigné relance en premier. Quand tous ont lancé, le joueur le plus proche marque un point. Jouez 10 manches en déplaçant le cochonnet. Le joueur à 10 points gagne.",duree:"12 min",materiel:"Sacs de fèves, petit objet coloré",intensite:"Faible"},
// ===== LOCOMOTION ET ATHLÉTISME (20 jeux) =====
{cat:"Locomotion et athlétisme",titre:"Décathlon Miniature",desc:"Créez 10 stations athlétiques : sprint 20m, saut en longueur sans élan, lancer de sac de fèves, slalom, saut en hauteur, lancer de précision, course à reculons, triple saut, lancer de frisbee et course de haies. Chaque joueur reçoit un score de 1 à 5 par station. Additionnez les scores. Le joueur avec le total le plus élevé gagne le décathlon.",duree:"20 min",materiel:"Cônes, sacs de fèves, corde, frisbees, cerceaux",intensite:"Élevé"},
{cat:"Locomotion et athlétisme",titre:"Course Tempo",desc:"Les joueurs courent autour du gymnase en suivant un rythme musical. Quand la musique est lente, ils marchent. Quand elle accélère, ils courent. Quand elle s'arrête, ils s'immobilisent comme des statues (le dernier fait 5 squats). L'enseignant varie les tempos et ajoute des consignes : musique grave = courir accroupi, musique aiguë = courir sur la pointe des pieds.",duree:"10 min",materiel:"Musique, haut-parleur",intensite:"Élevé"},
{cat:"Locomotion et athlétisme",titre:"Saut en Longueur Progressif",desc:"Tracez des lignes au sol à distances croissantes (1m, 1.5m, 2m, 2.5m, 3m). Les joueurs sautent à pieds joints depuis la ligne de départ. Quand un joueur réussit une distance, il passe à la suivante. Trois échecs consécutifs éliminent le joueur. Le dernier encore en compétition gagne. Insistez sur la technique : flexion des genoux, balancement des bras, réception pieds à plat.",duree:"12 min",materiel:"Ruban adhésif au sol, tapis de réception",intensite:"Moyen"},
{cat:"Locomotion et athlétisme",titre:"Le Marathon Coopératif",desc:"Toute la classe court ensemble pour cumuler collectivement la distance d'un marathon (42 km). Chaque tour de gymnase vaut environ 100 mètres. Les joueurs courent à leur rythme et comptent leurs tours. Un compteur au tableau additionne les tours. L'objectif est d'atteindre 420 tours ensemble. Encouragez les plus rapides à motiver les plus lents.",duree:"15 min",materiel:"Tableau, craie ou marqueur",intensite:"Élevé"},
{cat:"Locomotion et athlétisme",titre:"Course de Haies Créative",desc:"Installez un parcours avec des objets variés : cônes à enjamber, cordes à sauter par-dessus, bancs à franchir latéralement, tapis à rouler dessus et cerceaux à traverser en sautant. Les joueurs font le parcours individuellement chronométrés. Trois essais, le meilleur temps compte. Variante : parcours à reculons ou en portant un ballon.",duree:"15 min",materiel:"Cônes, cordes, bancs, tapis, cerceaux, chronomètre",intensite:"Élevé"},
{cat:"Locomotion et athlétisme",titre:"Le Lièvre et la Tortue",desc:"En paires, un joueur est le lièvre et l'autre la tortue. La tortue court à rythme constant. Le lièvre sprinte puis s'arrête. L'enseignant siffle toutes les 30 secondes : au sifflet, le lièvre doit être devant la tortue sinon il perd un point. Le lièvre doit gérer son énergie entre sprints et pauses. Après 5 minutes, inversez les rôles. Le joueur avec le moins de points perdus gagne.",duree:"12 min",materiel:"Sifflet",intensite:"Élevé"},
{cat:"Locomotion et athlétisme",titre:"Le Biathlon",desc:"Les joueurs alternent entre course et lancer de précision. Ils courent 2 tours de gymnase puis s'arrêtent à la station de tir : toucher 3 cônes-cibles à 4 mètres avec des sacs de fèves. Chaque cible manquée = un tour de pénalité. Puis ils repartent pour 2 tours et un autre tir. Le parcours comprend 3 arrêts de tir. Le joueur qui termine en premier gagne.",duree:"15 min",materiel:"Sacs de fèves, cônes cibles, cônes de parcours",intensite:"Élevé"},
{cat:"Locomotion et athlétisme",titre:"Course à Obstacles Ninja",desc:"Créez un parcours spectaculaire : ramper sous des cordes, escalader un espalier, traverser des cerceaux en sautant, marcher sur un banc inversé, se suspendre à une barre 10 secondes, rouler sur un tapis et sprinter jusqu'au cône final. Chronométrez chaque joueur. Les joueurs qui touchent un obstacle ou tombent sont éliminés. Le meilleur temps sans erreur gagne le titre de Ninja Warrior.",duree:"15 min",materiel:"Cordes, cerceaux, bancs, tapis, chronomètre",intensite:"Élevé"},
{cat:"Locomotion et athlétisme",titre:"Sprint Réaction",desc:"Les joueurs se placent en ligne. L'enseignant donne des commandes : un coup de sifflet = sprint avant 10m, deux coups = sprint arrière 5m, claquement de mains = latéral à droite, deux claquements = latéral à gauche, silence = s'immobiliser. Enchaînez rapidement. Les joueurs qui se trompent font 3 burpees. Après 5 minutes, le joueur avec le moins d'erreurs gagne.",duree:"10 min",materiel:"Sifflet",intensite:"Élevé"},
{cat:"Locomotion et athlétisme",titre:"Le Triathlon du Gymnase",desc:"Trois épreuves enchaînées : courir 5 tours de gymnase, faire 20 sauts à la corde, ramper en commando sur 10 mètres de tapis. Le chronomètre part au début et s'arrête à la fin. Chaque joueur fait le triathlon individuellement. Les autres encouragent. Le meilleur temps gagne. Variante : ajouter une 4e épreuve de lancer de précision.",duree:"15 min",materiel:"Cordes à sauter, tapis, chronomètre",intensite:"Élevé"},
{cat:"Locomotion et athlétisme",titre:"La Course des Animaux",desc:"L'enseignant appelle un animal et les joueurs traversent le gymnase dans ce style : kangourou = sauts pieds joints, ours = quatre pattes, crabe = latéral en crabe, grenouille = sauts accroupis, guépard = sprint, serpent = ramper, flamant = un pied. Le premier à traverser correctement gagne un point. Après 10 animaux, le joueur avec le plus de points gagne.",duree:"10 min",materiel:"Aucun",intensite:"Élevé"},
{cat:"Locomotion et athlétisme",titre:"Course Relais Progressif",desc:"En équipes de 5 sur une ligne de départ. Le premier court 1 tour et revient toucher la main du deuxième. Le deuxième court 2 tours. Le troisième 3, le quatrième 4, le cinquième 5. L'équipe doit gérer stratégiquement qui court quoi. L'équipe qui termine en premier gagne. Variante : commencer par 5 tours et descendre à 1.",duree:"15 min",materiel:"Cônes",intensite:"Élevé"},
{cat:"Locomotion et athlétisme",titre:"Le Parcours du Combattant",desc:"Parcours militaire : sprinter 10m, faire 10 jumping jacks, ramper sous un filet, monter et descendre un banc 5 fois, sauter par-dessus 5 cônes, porter un sac lesté sur 5m, rouler sur un tapis et sprinter jusqu'à l'arrivée. Les joueurs partent toutes les 30 secondes. Trois essais, meilleur temps compte. Le plus rapide gagne le titre de combattant suprême.",duree:"15 min",materiel:"Cônes, cordes, bancs, sacs, tapis, chronomètre",intensite:"Élevé"},
{cat:"Locomotion et athlétisme",titre:"Le Défi Corde à Sauter",desc:"Chaque joueur a une corde à sauter. Défis progressifs : sauts basiques, alternés, sur un pied, croisés devant, doubles tours, à reculons, les yeux fermés. Chaque joueur qui réussit avance d'un niveau. Après 10 minutes, le joueur au niveau le plus élevé gagne. Variante : défi de durée — qui peut sauter sans arrêt le plus longtemps.",duree:"12 min",materiel:"Cordes à sauter",intensite:"Élevé"},
{cat:"Locomotion et athlétisme",titre:"Relais Navette",desc:"En équipes de 4, allers-retours de plus en plus longs. Placez des cônes à 5m, 10m, 15m et 20m. Le premier court au cône de 5m et revient, puis touche le suivant qui court au 10m, etc. Quand on atteint 20m, on redescend. L'équipe qui termine la navette complète en premier gagne. Variante : toucher le cône avant de revenir.",duree:"10 min",materiel:"Cônes",intensite:"Élevé"},
{cat:"Locomotion et athlétisme",titre:"Le Cross-Fit Junior",desc:"Circuit de 6 stations : 10 squats, 10 pompes modifiées, 20 mountain climbers, planche 20 secondes, 10 fentes alternées, 15 abdominaux. Les joueurs font 30 secondes par station avec 15 secondes de transition. Faites 3 tours complets. Les joueurs comptent leurs répétitions totales. Le joueur avec le plus de répétitions gagne.",duree:"15 min",materiel:"Tapis, chronomètre",intensite:"Élevé"},
{cat:"Locomotion et athlétisme",titre:"Le Sprint Musical",desc:"Les joueurs courent en cercle. Quand la musique s'arrête, l'enseignant crie une action : sprint 10m, saut en étoile, roulade avant sur tapis, marche en canard, course genoux hauts. Les joueurs exécutent l'action puis reprennent la course au retour de la musique. Le joueur qui n'a jamais raté une action gagne. Variante : élimination pour le dernier à réagir.",duree:"10 min",materiel:"Musique, haut-parleur",intensite:"Élevé"},
{cat:"Locomotion et athlétisme",titre:"L'Escalier de Vitesse",desc:"Placez une échelle d'agilité au sol (ou dessinez-la avec du ruban). Les joueurs passent à travers avec différents patterns : un pied par case, deux pieds par case, latéralement, en sautant, en croisé. Chronométrez chaque passage. Le joueur avec le meilleur temps moyen gagne. Organisez des courses en duel : deux échelles côte à côte.",duree:"12 min",materiel:"Échelle d'agilité ou ruban adhésif, chronomètre",intensite:"Élevé"},
{cat:"Locomotion et athlétisme",titre:"Le Saut Créatif",desc:"Placez des cerceaux au sol en différents patterns. Les joueurs traversent en utilisant un type de saut différent pour chaque section : pieds joints, un pied gauche, un pied droit, alternés, croisé, saut avec demi-tour. Chronométrez la traversée complète. Le joueur le plus rapide sans erreur gagne. Variante : les joueurs créent leurs propres patterns pour les autres.",duree:"10 min",materiel:"Cerceaux, chronomètre",intensite:"Moyen"},
{cat:"Locomotion et athlétisme",titre:"Course à Trois Jambes",desc:"En paires, les joueurs attachent leur jambe intérieure ensemble avec un foulard. Ils doivent courir du point A au point B en se coordonnant. Commencez par de la marche puis augmentez à la course. Organisez un tournoi entre les paires. Changez de partenaire à chaque manche pour développer l'adaptabilité. Variante : parcours en slalom entre des cônes.",duree:"10 min",materiel:"Foulards, cônes",intensite:"Moyen"},
// ===== OPPOSITION ET DUEL (20 jeux) =====
{cat:"Opposition et duel",titre:"Sumo Poussée",desc:"Tracez un cercle de 2 mètres avec des cônes. Deux joueurs face à face au centre, mains sur les épaules de l'adversaire. Chaque joueur pousse pour faire sortir l'autre du cercle. Les pieds restent au sol, pas de croc-en-jambe. Le premier à mettre un pied hors du cercle perd. Placez des tapis autour pour la sécurité. Tournoi à élimination simple.",duree:"12 min",materiel:"Cônes ou ruban, tapis",intensite:"Élevé"},
{cat:"Opposition et duel",titre:"Combat de Coqs",desc:"Deux joueurs face à face, debout sur un pied, bras croisés sur la poitrine. Ils sautillent et se poussent épaule contre épaule pour déstabiliser l'adversaire. Le premier à poser son deuxième pied perd. Interdiction d'utiliser les mains. Duels de 30 secondes. Si personne ne tombe, c'est match nul. Organisez un tournoi par catégorie.",duree:"10 min",materiel:"Tapis",intensite:"Élevé"},
{cat:"Opposition et duel",titre:"Tir à la Corde",desc:"Deux équipes de 5-6 saisissent chacune un bout d'une longue corde. Un foulard est attaché au centre et une ligne est tracée au sol. Les deux équipes tirent la corde vers leur côté. L'équipe qui amène le foulard de son côté de la ligne gagne. Manches de 30 secondes maximum. Variante : tirer assis au sol ou d'une seule main.",duree:"10 min",materiel:"Longue corde, foulard, ruban au sol",intensite:"Élevé"},
{cat:"Opposition et duel",titre:"Le Duel des Chevaliers",desc:"Deux joueurs face à face, chacun debout sur un banc de gymnase. Chacun tient une frite de piscine. Ils essaient de déstabiliser l'adversaire en frappant doucement sur le torse ou les épaules, jamais la tête. Le premier à descendre du banc perd. Pas de coups violents. Duels de 30 secondes. Le gagnant affronte le prochain challenger.",duree:"12 min",materiel:"Bancs ou tapis, frites de piscine",intensite:"Moyen"},
{cat:"Opposition et duel",titre:"Bras de Fer Debout",desc:"Deux joueurs face à face, main droite serrée, pied droit contre pied droit (côtés extérieurs se touchent). Chaque joueur tire et pousse la main de l'adversaire pour le faire bouger ses pieds. Le premier à déplacer un pied perd. L'autre main reste derrière le dos. Manches de 15 secondes. Tournoi main droite puis main gauche.",duree:"10 min",materiel:"Aucun",intensite:"Moyen"},
{cat:"Opposition et duel",titre:"Le Foulard du Samouraï",desc:"Deux joueurs face à face, chacun avec un foulard dans la ceinture arrière. Chaque joueur doit attraper le foulard adverse tout en protégeant le sien. Interdiction de tenir son propre foulard. Zone délimitée de 4x4 mètres. Chaque duel dure 30 secondes maximum. Organisez un tournoi à double élimination.",duree:"12 min",materiel:"Foulards, cônes",intensite:"Élevé"},
{cat:"Opposition et duel",titre:"Badminton Duel",desc:"Installez 4-5 terrains miniatures de 2x3 mètres délimités par des cônes. Duels en 5 points : servir par en-dessous, le volant passe au-dessus d'une corde. Un point quand le volant touche le sol dans le terrain adverse. Le perdant cède sa place au prochain challenger. Le joueur avec le plus de victoires en 15 minutes est champion.",duree:"15 min",materiel:"Raquettes de badminton, volants, cônes, corde",intensite:"Moyen"},
{cat:"Opposition et duel",titre:"Le Cercle de Force",desc:"Tracez un cercle de 3 mètres. Deux joueurs dos à dos au centre, bras entrelacés. Chaque joueur pousse avec son dos pour forcer l'adversaire à sortir du cercle. Pas le droit de se retourner ou de lâcher les bras. Le premier à avoir un pied hors du cercle perd. Matchs de 20 secondes. Variante : côte à côte en poussant avec l'épaule.",duree:"10 min",materiel:"Cônes ou ruban, tapis",intensite:"Élevé"},
{cat:"Opposition et duel",titre:"Roche-Papier-Ciseaux Sportif",desc:"Deux équipes en file face à face au centre du gymnase. Le premier joueur de chaque file fait roche-papier-ciseaux. Le perdant court vers son mur de sécurité pendant que le gagnant le poursuit. Si le poursuivant le touche avant le mur, son équipe marque un point. L'équipe à 10 points gagne. Variante : le perdant fait un exercice au lieu de courir.",duree:"12 min",materiel:"Aucun",intensite:"Élevé"},
{cat:"Opposition et duel",titre:"Le Combat des Tortues",desc:"Deux joueurs à quatre pattes face à face sur un tapis. Chaque joueur essaie de retourner l'adversaire sur le dos. On peut pousser, tirer doucement et contourner. Interdiction de frapper, griffer ou tirer les vêtements. Le premier retourné perd. Matchs de 30 secondes. Si personne n'est retourné, c'est match nul.",duree:"10 min",materiel:"Tapis de gymnastique",intensite:"Élevé"},
{cat:"Opposition et duel",titre:"Escrime au Ballon",desc:"Deux joueurs face à face, chacun tient un ballon en mousse d'une main. Ils tentent de toucher l'adversaire avec leur ballon tout en esquivant. Un toucher au torse = 1 point. Le joueur à 3 points gagne le duel. Il faut garder le ballon en main, pas le lancer. Zone de 3x3 mètres. Tournoi à élimination.",duree:"12 min",materiel:"Ballons en mousse",intensite:"Moyen"},
{cat:"Opposition et duel",titre:"La Lutte des Pouces Géante",desc:"Deux joueurs face à face se tiennent par la main droite. Chacun a un foulard coincé sous le pouce. L'objectif est de retirer le foulard de l'adversaire avec sa main libre tout en protégeant le sien. Les mains droites restent jointes. Le premier à retirer le foulard adverse gagne. Matchs de 20 secondes. Tournoi rapide avec changement d'adversaire.",duree:"10 min",materiel:"Foulards",intensite:"Moyen"},
{cat:"Opposition et duel",titre:"Le Duel de Rapidité",desc:"Deux joueurs face à face à 2 mètres. Un sac de fèves est posé au sol entre eux. L'enseignant donne des consignes (touchez vos genoux, votre tête, vos pieds, tournez). Quand il crie SAC, les deux plongent pour attraper le sac. Le premier à le saisir gagne. Chaque paire fait 5 duels. Le joueur avec le plus de sacs gagne. Changez de partenaire après chaque série.",duree:"10 min",materiel:"Sacs de fèves",intensite:"Moyen"},
{cat:"Opposition et duel",titre:"Le Roi de la Montagne",desc:"Placez un gros tapis au centre. Un joueur est le roi au sommet. Les challengers viennent un par un. Le roi et le challenger se poussent épaule contre épaule ou dos contre dos (pas de mains sur le corps). Si le roi est délogé, le challenger devient roi. Le roi qui résiste le plus de challengers consécutifs gagne. Sécurité : tapis tout autour.",duree:"12 min",materiel:"Gros tapis, tapis de sécurité autour",intensite:"Élevé"},
{cat:"Opposition et duel",titre:"Duel de Traction",desc:"Deux joueurs face à face, chacun tenant un bout d'un foulard. Ligne au sol entre eux. Chaque joueur tire le foulard vers lui. Le premier à tirer l'adversaire de son côté gagne. Les pieds doivent glisser, pas de sauts. Variante à une main puis à deux mains. Duels de 15 secondes. Tournoi avec différentes catégories de poids.",duree:"10 min",materiel:"Foulards, ruban au sol",intensite:"Élevé"},
{cat:"Opposition et duel",titre:"La Course en Duel",desc:"Deux joueurs dos à dos au centre. L'enseignant appelle un côté (gauche ou droite). Le joueur du côté appelé sprinte vers son mur pendant que l'autre le poursuit. Si le poursuivant touche le fuyard avant le mur, il gagne un point. L'enseignant ajoute des feintes. Après 10 appels, le joueur avec le plus de points gagne.",duree:"10 min",materiel:"Aucun",intensite:"Élevé"},
{cat:"Opposition et duel",titre:"Le Ping-Pong au Sol",desc:"Deux joueurs face à face assis au sol, jambes écartées, pieds se touchant. Ils se font rouler une balle de tennis. Chaque joueur essaie de faire passer la balle entre les jambes de l'adversaire. L'adversaire bloque avec ses mains. Un point quand la balle passe. Premier à 5 points gagne. Les joueurs ne bougent pas leurs jambes. Variante : main non dominante uniquement.",duree:"10 min",materiel:"Balles de tennis",intensite:"Faible"},
{cat:"Opposition et duel",titre:"Le Miroir Inversé",desc:"Deux joueurs face à face. Le meneur fait des mouvements et l'autre doit faire le mouvement OPPOSÉ : si le meneur va à gauche, l'autre va à droite; s'il s'accroupit, l'autre saute. Chaque erreur donne un point au meneur. Après 1 minute, on inverse. Le joueur avec le moins d'erreurs après 2 manches gagne. Variante : accélérer progressivement.",duree:"10 min",materiel:"Aucun",intensite:"Moyen"},
{cat:"Opposition et duel",titre:"Le Ballon Contesté",desc:"Deux joueurs face à face, un ballon au sol entre eux, mains sur les genoux. L'enseignant donne des instructions rapides. Au mot BALLON, les deux plongent pour l'attraper. Le joueur qui le saisit en premier marque. S'ils le saisissent en même temps, roche-papier-ciseaux. Premier à 5 points gagne.",duree:"10 min",materiel:"Ballons",intensite:"Moyen"},
{cat:"Opposition et duel",titre:"Le Territoire",desc:"Chaque joueur se place dans un cerceau posé au sol (son territoire) en grille à 1 mètre les uns des autres. Un pied doit toujours rester dans son cerceau. Les joueurs tentent de déstabiliser leurs voisins en les tirant ou poussant doucement (mains sur épaules seulement). Le joueur qui sort son pied est éliminé et retire son cerceau. Le dernier dans son cerceau gagne.",duree:"10 min",materiel:"Cerceaux",intensite:"Moyen"},
// ===== JEUX DE RELAIS (20 jeux) =====
{cat:"Jeux de relais",titre:"Relais Classique Chrono",desc:"Équipes de 5 en file. Le premier court au cône (15m), le contourne et revient toucher la main du suivant. Chronométrez chaque équipe. Faites 3 manches, meilleur temps compte. Variante : courir à reculons, en pas chassés ou avec un dribble de ballon.",duree:"10 min",materiel:"Cônes, chronomètre",intensite:"Élevé"},
{cat:"Jeux de relais",titre:"Relais Déménageur",desc:"Placez 10 objets variés d'un côté du gymnase pour chaque équipe. Les joueurs courent un par un pour transporter un objet à la fois vers la zone d'arrivée. Certains objets sont faciles et d'autres plus compliqués (cerceau sur la tête). Si un objet tombe, le joueur le ramasse et continue. L'équipe qui déménage tous ses objets en premier gagne.",duree:"12 min",materiel:"Balles, sacs de fèves, cônes, cerceaux",intensite:"Élevé"},
{cat:"Jeux de relais",titre:"Relais Brouette",desc:"En paires dans des équipes de 6. Le premier joueur en position de brouette (mains au sol) et son partenaire lui tient les chevilles. Ils avancent au cône (10m), échangent les rôles pour le retour. La paire suivante part. L'équipe dont les 3 paires complètent le trajet en premier gagne. La brouette garde les bras tendus.",duree:"10 min",materiel:"Cônes",intensite:"Élevé"},
{cat:"Jeux de relais",titre:"Relais Habillage",desc:"Au cône se trouve un sac de vêtements amples : grand chandail, chapeau, gants et écharpe. Le premier joueur court, enfile tout, revient toucher le suivant, enlève les vêtements et le suivant court les remettre dans le sac. Le troisième repart les enfiler. L'équipe qui termine ses rotations en premier gagne.",duree:"12 min",materiel:"Vêtements amples, sacs, cônes",intensite:"Élevé"},
{cat:"Jeux de relais",titre:"Relais de l'Oeuf",desc:"Chaque joueur transporte une balle de tennis sur une raquette de badminton du départ au cône (10m) et revient sans la faire tomber. Si la balle tombe, le joueur la replace et repart du point de chute. Au retour, il passe la raquette au suivant. L'équipe qui termine en premier gagne. Variante : slalom entre des cônes.",duree:"10 min",materiel:"Raquettes de badminton, balles de tennis, cônes",intensite:"Moyen"},
{cat:"Jeux de relais",titre:"Relais Kangourou",desc:"Les joueurs tiennent un ballon entre leurs genoux et sautent comme un kangourou jusqu'au cône et retour. Si le ballon tombe, le joueur le replace et repart du point de chute. Au retour, il passe le ballon au suivant. L'équipe qui termine en premier gagne. Variante : ballon entre les chevilles ou sur la tête sans les mains.",duree:"10 min",materiel:"Ballons, cônes",intensite:"Élevé"},
{cat:"Jeux de relais",titre:"Relais Tunnel",desc:"Les joueurs se placent debout jambes écartées en file. Le dernier rampe à travers le tunnel formé par les jambes de ses coéquipiers. Arrivé à l'avant, il se place jambes écartées et le nouveau dernier rampe. L'équipe avance vers le mur opposé. La première dont le premier joueur original touche le mur gagne.",duree:"10 min",materiel:"Aucun",intensite:"Élevé"},
{cat:"Jeux de relais",titre:"Relais Mathématique",desc:"Au cône, un tableau blanc, un marqueur et des cartes avec des problèmes mathématiques. Le joueur court, pige une carte, résout le problème. Si c'est correct, il revient et le suivant part. Si c'est faux, il fait 5 jumping jacks puis réessaie. L'équipe qui résout toutes ses 10 cartes en premier gagne.",duree:"12 min",materiel:"Tableaux blancs, marqueurs, cartes mathématiques, cônes",intensite:"Élevé"},
{cat:"Jeux de relais",titre:"Relais Saut de Grenouille",desc:"Les joueurs en file accroupis. Le dernier saute par-dessus chaque coéquipier accroupi (saute-mouton) jusqu'à l'avant, puis s'accroupit. Le nouveau dernier fait la même chose. L'équipe avance vers le mur opposé. La première à l'atteindre gagne. Les joueurs accroupis gardent la tête basse et les sauteurs placent les mains sur le dos.",duree:"10 min",materiel:"Tapis (optionnel)",intensite:"Élevé"},
{cat:"Jeux de relais",titre:"Relais à l'Aveugle",desc:"En paires dans chaque équipe. Le guide voit et le coureur a les yeux bandés. Le guide donne des instructions vocales pour que le coureur aveugle marche au cône et revienne sans toucher les obstacles. Si un obstacle est touché, la paire repart du début. L'équipe qui termine en premier gagne. Variante : le guide ne peut dire que 3 mots (gauche, droite, stop).",duree:"12 min",materiel:"Bandeaux, cônes",intensite:"Moyen"},
{cat:"Jeux de relais",titre:"Relais Multi-Sports",desc:"4 stations en séquence par équipe. Station 1 : dribbler un ballon aller-retour (5m). Station 2 : 5 passes contre le mur au soccer. Station 3 : lancer un sac de fèves dans un cerceau (réussir 1 sur 3). Station 4 : 10 sauts à la corde. Le joueur complète les 4 stations puis revient toucher le suivant. L'équipe qui termine en premier gagne.",duree:"15 min",materiel:"Ballons, sacs de fèves, cerceaux, cordes à sauter",intensite:"Élevé"},
{cat:"Jeux de relais",titre:"Relais Pompier",desc:"Un seau de balles à une extrémité et un seau vide à l'autre. Les joueurs courent avec un gobelet pour transporter les balles une à la fois. L'équipe qui remplit son seau vide en premier gagne. Variante extérieure avec de l'eau : gobelet percé, l'équipe avec le plus d'eau dans le seau d'arrivée après 5 minutes gagne.",duree:"10 min",materiel:"Seaux, balles, gobelets",intensite:"Élevé"},
{cat:"Jeux de relais",titre:"Relais Puzzle",desc:"Au cône se trouve un puzzle de 12 pièces. Un joueur à la fois court et place une seule pièce. Il revient et le suivant part placer la suivante. Les joueurs doivent mémoriser l'état du puzzle à chaque passage. L'équipe qui complète son puzzle en premier gagne. Si une pièce est mal placée, le joueur suivant corrige.",duree:"12 min",materiel:"Puzzles simples, cônes",intensite:"Moyen"},
{cat:"Jeux de relais",titre:"Relais Dos à Dos",desc:"En paires dos à dos avec un ballon coincé entre leurs dos (sans les mains). Ils marchent ou courent au cône et reviennent. Si le ballon tombe, ils le replacent et repartent du point de chute. La paire suivante part au retour. L'équipe qui termine en premier gagne. Variante : ballon entre les fronts en marchant face à face.",duree:"10 min",materiel:"Ballons, cônes",intensite:"Moyen"},
{cat:"Jeux de relais",titre:"Relais Construction",desc:"Des blocs au centre du gymnase. Un joueur à la fois court prendre un bloc et revient le poser pour construire une pyramide spécifique (4 en base, 3 au 2e, 2 au 3e, 1 au sommet) montrée sur une image. Si la pyramide tombe, l'équipe la reconstruit. La première équipe à compléter sa pyramide gagne.",duree:"12 min",materiel:"Blocs ou cônes, image modèle",intensite:"Élevé"},
{cat:"Jeux de relais",titre:"Relais Crabe",desc:"Les joueurs se déplacent en position de crabe (mains et pieds, ventre vers le haut) jusqu'au cône et retour. Au retour, ils touchent le pied du suivant. Ce relais travaille intensément les bras, les jambes et les abdominaux. Variante : placer un sac de fèves sur le ventre pendant le déplacement — s'il tombe, on le replace.",duree:"10 min",materiel:"Cônes",intensite:"Élevé"},
{cat:"Jeux de relais",titre:"Relais Alphabet",desc:"Au cône, un ensemble de lettres en carton. L'enseignant annonce un mot (ex: SPORT). Le premier joueur court trouver la lettre S, la ramène. Le deuxième cherche le P, etc. Les joueurs trouvent les lettres dans l'ordre du mot. L'équipe qui épelle le mot en premier gagne. Jouez 5 manches avec des mots différents.",duree:"12 min",materiel:"Lettres en carton, cônes",intensite:"Élevé"},
{cat:"Jeux de relais",titre:"Relais Sandwich",desc:"Trois joueurs partent ensemble. Le joueur du milieu est soulevé légèrement par les deux autres qui le tiennent par les bras. Le trio se rend au cône et revient. Le trio suivant part. L'équipe qui termine en premier gagne. Changez les rôles à chaque manche.",duree:"10 min",materiel:"Cônes",intensite:"Élevé"},
{cat:"Jeux de relais",titre:"Relais Mission Secrète",desc:"Chaque équipe reçoit 5 enveloppes numérotées contenant un défi. Le premier joueur court au cône, ouvre l'enveloppe 1 et fait le défi (ex: 10 squats, nommer 3 pays d'Afrique). L'enseignant valide. Si le défi est raté, un tour de pénalité puis nouvel essai. L'équipe qui complète les 5 missions en premier gagne.",duree:"15 min",materiel:"Enveloppes avec défis, cônes",intensite:"Élevé"},
{cat:"Jeux de relais",titre:"Relais Équilibre",desc:"Parcours d'équilibre : marcher sur un banc inversé, passer d'un cerceau à l'autre sans toucher le sol, marcher sur une ligne de ruban au sol, se tenir sur un pied 5 secondes sur un tapis. Si le joueur tombe ou perd l'équilibre, il recommence la section. Au retour, il touche la main du suivant. L'équipe qui termine en premier gagne.",duree:"12 min",materiel:"Bancs, cerceaux, ruban adhésif, tapis",intensite:"Moyen"},
// ===== DÉFIS ET CIRCUITS (20 jeux) =====
{cat:"Défis et circuits",titre:"Le Circuit des Champions",desc:"8 stations en cercle, 3 minutes par station : corde à sauter, lancer de précision, slalom, planche et gainage, dribble de ballon, sauts dans cerceaux, pompes et squats, équilibre sur un pied. Les joueurs notent leur score à chaque station. Le meilleur score total est le champion du circuit.",duree:"20 min",materiel:"Cordes à sauter, sacs de fèves, cerceaux, cônes, ballons, tapis",intensite:"Élevé"},
{cat:"Défis et circuits",titre:"Le Défi 100",desc:"La classe doit compléter 100 répétitions collectives de 5 exercices : 100 squats, 100 pompes, 100 abdominaux, 100 jumping jacks et 100 fentes. Chaque joueur fait autant qu'il peut et rapporte son chiffre au compteur central. L'enseignant additionne au tableau. L'objectif est de terminer les 500 répétitions le plus vite possible. Essayez de battre le record de classe.",duree:"15 min",materiel:"Tapis, tableau, chronomètre",intensite:"Élevé"},
{cat:"Défis et circuits",titre:"Ninja Warrior Junior",desc:"Parcours d'obstacles spectaculaire : ramper sous des bancs, escalader l'espalier, traverser des cerceaux en sautant, marcher sur un banc inversé, se suspendre à une barre 10 secondes, rouler sur un tapis et sprinter jusqu'au cône final. Chronométrez chaque joueur. Ceux qui touchent un obstacle sont éliminés. Le meilleur temps sans erreur gagne le titre de Ninja Warrior.",duree:"20 min",materiel:"Bancs, cerceaux, tapis, cônes, espalier, chronomètre",intensite:"Élevé"},
{cat:"Défis et circuits",titre:"Le Tabata du Gymnase",desc:"Entraînement en intervalles Tabata : 20 secondes d'effort intense, 10 secondes de repos, 8 rounds par exercice. Exercice 1 : burpees. Exercice 2 : mountain climbers. Exercice 3 : squats sautés. Exercice 4 : planche toucher d'épaule. Chaque exercice dure 4 minutes. Prenez 1 minute de repos entre les exercices. Le joueur avec le plus de répétitions totales gagne.",duree:"20 min",materiel:"Tapis, chronomètre ou musique Tabata",intensite:"Élevé"},
{cat:"Défis et circuits",titre:"La Roue des Défis",desc:"Grande roue en carton avec des sections numérotées de 1 à 10. Chaque numéro correspond à un défi : sprint 20m, 15 squats, 10 pompes, planche 30 secondes, 20 jumping jacks, course en crabe 10m, 10 burpees, corde à sauter 30 secondes, ramper 10m, saut en longueur 3 essais. Un joueur fait tourner la roue et toute la classe fait le défi. 10 tours de roue.",duree:"15 min",materiel:"Roue en carton, matériel varié, cordes à sauter, tapis",intensite:"Élevé"},
{cat:"Défis et circuits",titre:"Le Circuit Alphabet",desc:"Associez une lettre à un exercice (A=abdominaux, B=burpees, C=corde, D=dribble, etc.). L'enseignant épelle un mot et les joueurs font les exercices correspondants. 10 répétitions par lettre. En équipes de 4, tous doivent compléter le mot. L'équipe qui termine en premier gagne. Variante : les joueurs composent leur propre mot de 5 lettres max.",duree:"12 min",materiel:"Tableau avec correspondance lettre-exercice, matériel varié",intensite:"Élevé"},
{cat:"Défis et circuits",titre:"Le Parcours Arc-en-ciel",desc:"6 stations de couleurs en cercle. Rouge : force (pompes, squats). Orange : vitesse (sprints). Jaune : agilité (slalom, échelle). Vert : équilibre (un pied, poutre). Bleu : souplesse (étirements actifs). Violet : coordination (jonglerie, dribble). Les joueurs passent 2 minutes par station. Après un tour complet, ils ont traversé l'arc-en-ciel.",duree:"15 min",materiel:"Cônes de couleur, matériel varié par station",intensite:"Élevé"},
{cat:"Défis et circuits",titre:"Le Défi par Équipe",desc:"4 équipes reçoivent une fiche avec 10 défis dans n'importe quel ordre : 50 sauts groupés collectifs, chaque joueur fait 1 tour, pyramide de 10 cônes, 30 passes sans échapper le ballon, chaque joueur saute la corde 20 fois, traverser en crabe, lancer 5 sacs dans un cerceau, planche collective 30 secondes, résoudre un problème math, photo de groupe créative.",duree:"20 min",materiel:"Fiches, cônes, ballons, cordes à sauter, sacs de fèves, cerceaux",intensite:"Élevé"},
{cat:"Défis et circuits",titre:"L'Ironman du Gymnase",desc:"Parcours d'endurance en 3 épreuves enchaînées. Natation simulée : ramper en commando sur 20m de tapis. Vélo simulé : 20 tours de jambes en position couchée puis course en crabe 10m. Course : 5 tours de gymnase. Les joueurs partent toutes les 30 secondes. Le meilleur temps total gagne le titre d'Ironman.",duree:"15 min",materiel:"Tapis, chronomètre",intensite:"Élevé"},
{cat:"Défis et circuits",titre:"Le Défi Minute",desc:"L'enseignant annonce un défi par minute pendant 10 minutes. Les joueurs ont 60 secondes pour compléter chaque défi : 15 squats, 2 tours de gymnase, 10 pompes, 30 sauts à la corde, 3 lancers réussis dans un cerceau, etc. Les joueurs qui complètent le défi dans la minute gagnent un point. Le joueur avec 10 points est imbattable.",duree:"12 min",materiel:"Matériel varié, chronomètre",intensite:"Élevé"},
{cat:"Défis et circuits",titre:"Le Casino Sportif",desc:"5 stations avec un dé chacune. Le joueur lance le dé : 1=5 reps, 2=10, 3=15, 4=20, 5=25, 6=choix libre. Chaque station a un exercice : pompes, squats, abdos, burpees, corde à sauter. Les joueurs passent 2 minutes par station et font autant de lancers que possible.",duree:"12 min",materiel:"Dés, tapis, cordes à sauter",intensite:"Élevé"},
{cat:"Défis et circuits",titre:"Le Circuit des Continents",desc:"6 stations représentant les continents. Amérique : lancer de précision. Europe : dribble soccer et tir. Asie : kata de mouvements. Afrique : sprint 20m. Océanie : ramper. Antarctique : planche 30 secondes. Les joueurs passent 2 minutes par continent et collectent un tampon sur leur passeport. Le voyage complet donne un certificat de globe-trotter.",duree:"15 min",materiel:"Matériel varié par station, passeports en papier",intensite:"Élevé"},
{cat:"Défis et circuits",titre:"Le Parcours à Points",desc:"10 obstacles avec des points selon la difficulté. Facile (enjamber un cône) = 1 point. Moyen (traverser des cerceaux) = 2 points. Difficile (marcher sur un banc inversé) = 3 points. Expert (grimper l'espalier) = 5 points. Les joueurs choisissent leur parcours en 3 minutes et accumulent des points. Le joueur avec le plus de points sans erreur gagne.",duree:"15 min",materiel:"Cônes, cerceaux, bancs, espalier, tapis",intensite:"Élevé"},
{cat:"Défis et circuits",titre:"Le Défi des Records Personnels",desc:"Chaque joueur reçoit une fiche avec 8 défis : pompes max en 30 secondes, distance de saut en longueur, temps pour 2 tours de gymnase, lancers réussis sur 10, record de corde à sauter, temps en planche, squats en 1 minute, dribbles sans perdre le ballon. Chaque joueur tente de battre ses propres records. On refait le test plus tard pour mesurer les progrès.",duree:"20 min",materiel:"Fiches, crayons, chronomètre, ballon, corde à sauter, tapis",intensite:"Élevé"},
{cat:"Défis et circuits",titre:"Le Crossfit Équipe",desc:"En équipes de 4, complétez le WOD : 40 squats (10 chacun), 100m de course (25m chacun), 20 pompes (5 chacun), 60 jumping jacks (15 chacun) et planche 1 minute (15 secondes chacun). Les joueurs se relaient sans arrêt du chrono. L'équipe qui termine en premier gagne. Variante : chaque joueur fait tous les exercices.",duree:"12 min",materiel:"Tapis, chronomètre",intensite:"Élevé"},
{cat:"Défis et circuits",titre:"Le Parcours Commando",desc:"Parcours militaire chronométré : ramper sous une corde à 30cm du sol sur 5m, zigzag entre 8 cônes, sauter par-dessus 3 bancs, 10 squats, ramper sur le ventre 3m, porter un sac lesté 5m, sprint final 10m. Un joueur à la fois, meilleur temps gagne ses galons de commandant. Variante : parcours en duo à moins de 2m l'un de l'autre.",duree:"15 min",materiel:"Cordes, cônes, bancs, tapis, sacs, chronomètre",intensite:"Élevé"},
{cat:"Défis et circuits",titre:"Le Bingo Sportif",desc:"Chaque joueur reçoit une carte de bingo 5x5 avec des exercices dans les cases. Les joueurs complètent les exercices pour cocher les cases. L'objectif est de réaliser une ligne de 5 cases le plus vite possible. Le premier à crier BINGO montre sa carte et l'enseignant valide. Variante : compléter la carte entière comme défi ultime.",duree:"15 min",materiel:"Cartes bingo imprimées, crayons, matériel varié",intensite:"Élevé"},
{cat:"Défis et circuits",titre:"Le Survivor",desc:"Défi d'élimination progressive. Épreuve 1 : tous courent 2 tours (les 3 derniers sont éliminés et deviennent juges). Épreuve 2 : lancer un sac dans un cerceau. Épreuve 3 : planche le plus longtemps. Continuez avec des défis de force, vitesse, précision et équilibre. Le dernier debout est le Survivor de la classe.",duree:"20 min",materiel:"Cônes, sacs de fèves, cerceaux, tapis, chronomètre",intensite:"Élevé"},
{cat:"Défis et circuits",titre:"Le Circuit Musical",desc:"6 stations en cercle. La musique joue et les joueurs font l'exercice de leur station. Quand la musique s'arrête, tout le monde court à la station suivante. Stations : sauts étoile, pompes, sprint sur place, abdos, corde à sauter, squats. Variante : l'enseignant crie un nombre de stations à sauter.",duree:"12 min",materiel:"Musique, haut-parleur, cordes à sauter, tapis",intensite:"Élevé"},
{cat:"Défis et circuits",titre:"Le Défi Carte à Jouer",desc:"Utilisez un jeu de cartes standard. Chaque symbole = un exercice : coeur=squats, carreau=pompes, trèfle=abdominaux, pique=burpees. Le chiffre = nombre de répétitions (figures=10, as=11). Un joueur pige et toute la classe fait l'exercice. En variante équipe, chaque équipe pige ses propres cartes. L'équipe qui finit ses 10 cartes en premier gagne.",duree:"15 min",materiel:"Jeu de cartes, tapis",intensite:"Élevé"},
// ===== JEUX CALMES (20 jeux) =====
{cat:"Jeux calmes",titre:"Le Mime Sportif",desc:"Un joueur pige une carte avec le nom d'un sport et doit le mimer sans parler. Les autres lèvent la main pour deviner. Le premier à deviner correctement marque un point et devient le prochain mime. Préparez 30 cartes avec des sports variés. Après 15 minutes, le joueur avec le plus de points gagne. Variante : mimer en équipes.",duree:"12 min",materiel:"Cartes avec noms de sports",intensite:"Faible"},
{cat:"Jeux calmes",titre:"Le Yoga des Guerriers",desc:"Guidez la classe dans une séance de yoga adaptée. Postures : l'arbre, le guerrier 1, 2 et 3, le chien tête en bas, la planche, le cobra, la montagne, le triangle et la chaise. Tenez chaque posture 20-30 secondes. Insistez sur la respiration : inspirer par le nez, expirer par la bouche. Terminez par 2 minutes de relaxation allongée. Excellent pour calmer un groupe.",duree:"15 min",materiel:"Tapis de gymnastique, musique douce (optionnel)",intensite:"Faible"},
{cat:"Jeux calmes",titre:"Jacques a Dit Avancé",desc:"Le classique Jacques a Dit avec des consignes plus complexes. Exemples : Jacques a dit touchez votre coude gauche avec votre main droite, Jacques a dit faites 3 pas de crabe vers la gauche. Les joueurs éliminés s'assoient et deviennent juges. Le dernier debout gagne. Accélérez les consignes pour augmenter la difficulté.",duree:"10 min",materiel:"Aucun",intensite:"Faible"},
{cat:"Jeux calmes",titre:"Le Chef d'Orchestre",desc:"Les joueurs sont assis en cercle. Un joueur (le détective) sort du gymnase. Le groupe choisit un chef d'orchestre qui initie discrètement des mouvements que tout le monde copie. Le détective revient et observe pour identifier le chef d'orchestre. Le groupe change de mouvement quand le chef change. Le détective a 3 essais. Si trouvé, le chef devient détective.",duree:"10 min",materiel:"Aucun",intensite:"Faible"},
{cat:"Jeux calmes",titre:"Le Jeu des Statues Vivantes",desc:"Les joueurs marchent librement. Quand la musique s'arrête, ils se figent en statue. L'enseignant appelle un thème (sport, animal, émotion, métier) et les joueurs se figent dans une posture représentant ce thème. L'enseignant élimine les statues les moins convaincantes. Les joueurs éliminés votent pour la meilleure statue. Le dernier debout est champion.",duree:"10 min",materiel:"Musique (optionnel)",intensite:"Faible"},
{cat:"Jeux calmes",titre:"Le Memory Physique",desc:"Placez 20 cônes retournés en grille 4x5. Sous chaque cône, un carton de couleur (10 paires). En équipes de 3, retournez 2 cônes à tour de rôle. Si les couleurs correspondent, l'équipe garde la paire et rejoue. Sinon, les cônes sont replacés. L'équipe avec le plus de paires gagne. Variante : les joueurs doivent sauter ou ramper jusqu'aux cônes.",duree:"12 min",materiel:"Cônes, cartons de couleurs",intensite:"Faible"},
{cat:"Jeux calmes",titre:"Le Twister Humain",desc:"Placez des cercles de 4 couleurs au sol en grille. L'enseignant appelle : main droite sur rouge, pied gauche sur bleu, etc. Les joueurs placent le membre sur la bonne couleur sans tomber. Si un joueur touche le sol avec autre chose que mains et pieds, il est éliminé. Le dernier en position gagne. Jouez en groupes de 4.",duree:"12 min",materiel:"Cercles de couleurs au sol ou tapis Twister",intensite:"Faible"},
{cat:"Jeux calmes",titre:"Le Téléphone Arabe Corporel",desc:"Les joueurs forment une file et tournent le dos. Le dernier invente un mouvement (lever le bras, toucher le genou, faire un cercle). Il tapote l'épaule du joueur devant qui se retourne et observe. Ce joueur reproduit le mouvement pour le suivant. Le mouvement passe de joueur en joueur. À la fin, comparez le mouvement final avec l'original. C'est souvent hilarant!",duree:"10 min",materiel:"Aucun",intensite:"Faible"},
{cat:"Jeux calmes",titre:"Le Jeu de Kim Sportif",desc:"Placez 15 objets sportifs sur un tapis (balle, raquette, cône, sifflet, corde, dossard, etc.). Les joueurs observent pendant 30 secondes. Ils ferment les yeux et l'enseignant retire 3 objets. Les joueurs ouvrent les yeux et identifient les objets manquants. Le premier à trouver les 3 gagne un point. Faites 5 manches.",duree:"10 min",materiel:"Objets sportifs variés, tapis",intensite:"Faible"},
{cat:"Jeux calmes",titre:"Le Jeu d'Équilibre Zen",desc:"Les joueurs tiennent des postures d'équilibre le plus longtemps possible. Posture 1 : debout sur un pied yeux ouverts 30 sec. Posture 2 : un pied yeux fermés 20 sec. Posture 3 : pointe des pieds bras en l'air 20 sec. Posture 4 : arbre yoga pied contre genou 30 sec. Chaque posture tenue = 1 point. Le joueur avec le plus de points après 8 postures gagne le titre de maître zen.",duree:"10 min",materiel:"Aucun",intensite:"Faible"},
{cat:"Jeux calmes",titre:"Le Dessin au Sol",desc:"En équipes de 4, les joueurs forment des lettres, chiffres ou formes avec leurs corps allongés au sol. L'enseignant appelle une lettre ou un chiffre et l'équipe a 20 secondes pour se positionner. Chaque forme réussie = 1 point. Variante avancée : former des mots complets. L'équipe avec le plus de points après 10 formes gagne.",duree:"10 min",materiel:"Aucun",intensite:"Faible"},
{cat:"Jeux calmes",titre:"Le Jeu de la Boussole",desc:"Les joueurs sont debout yeux fermés au centre du gymnase. L'enseignant appelle une direction (Nord = mur du fond, Sud = entrée, Est = droite, Ouest = gauche). Les joueurs pointent dans la bonne direction sans ouvrir les yeux. Ensuite, les joueurs marchent yeux fermés vers le mur annoncé. Le joueur le plus près du bon mur gagne le point.",duree:"10 min",materiel:"Aucun",intensite:"Faible"},
{cat:"Jeux calmes",titre:"Le Béret Immobile",desc:"Deux équipes assises face à face à 5 mètres. Un sac de fèves au centre. L'enseignant appelle un numéro et les deux joueurs correspondants se lèvent calmement, marchent (pas courir!) vers le centre et tentent de saisir le sac. Le joueur qui le saisit marche vers son équipe. L'autre peut le toucher avant qu'il s'assoie pour voler le point. Première équipe à 10 points gagne.",duree:"12 min",materiel:"Sac de fèves, dossards numérotés",intensite:"Faible"},
{cat:"Jeux calmes",titre:"La Relaxation Guidée",desc:"Les joueurs s'allongent sur des tapis yeux fermés. L'enseignant guide une relaxation progressive : contractez les orteils 5 secondes puis relâchez, les mollets, les cuisses, le ventre, les mains, les bras, les épaules, le visage. Ensuite, imaginez-vous dans un endroit calme. Restez immobiles 2 minutes. Ouvrez les yeux lentement. Excellent pour finir un cours ou calmer un groupe.",duree:"10 min",materiel:"Tapis de gymnastique, musique douce (optionnel)",intensite:"Faible"},
{cat:"Jeux calmes",titre:"Le Jeu des Différences",desc:"En paires, le joueur A observe le joueur B pendant 30 secondes. Le joueur A se retourne. Le joueur B modifie 3 choses sur son apparence (enlève un soulier, relève une manche, etc.). Le joueur A se retourne et a 30 secondes pour identifier les changements. Chaque changement trouvé = 1 point. Inversez les rôles. Le meilleur score après 3 manches gagne.",duree:"10 min",materiel:"Aucun",intensite:"Faible"},
{cat:"Jeux calmes",titre:"Le Morpion Géant",desc:"Tracez une grille de morpion 3x3 au sol avec du ruban. 2 équipes de 3 joueurs avec dossards de couleur. À tour de rôle, un joueur de chaque équipe marche et se place dans une case. L'objectif est d'aligner 3 joueurs de la même couleur. Si personne n'a gagné après 3 joueurs par équipe, on peut déplacer un joueur. Manches rapides de 2 minutes.",duree:"10 min",materiel:"Ruban adhésif, dossards 2 couleurs",intensite:"Faible"},
{cat:"Jeux calmes",titre:"Le Quiz Sportif Actif",desc:"Les joueurs sont assis en cercle. L'enseignant pose des questions sur le sport (ex: combien de joueurs au soccer? Quel sport utilise un volant?). Le premier à lever la main répond. Bonne réponse = 1 point. Mauvaise réponse = 5 jumping jacks. Préparez 30 questions. Le joueur avec le plus de points est champion du quiz sportif.",duree:"12 min",materiel:"Liste de questions",intensite:"Faible"},
{cat:"Jeux calmes",titre:"Le Pictionary Sportif",desc:"En équipes de 4-5. Un joueur vient voir un mot (sport, mouvement ou équipement). Il retourne à son équipe et dessine sur un tableau blanc sans parler. 30 secondes pour deviner. Si l'équipe devine, 1 point. Sinon, les autres équipes peuvent voler le point. Le dessinateur change à chaque tour. L'équipe à 10 points gagne.",duree:"12 min",materiel:"Tableaux blancs, marqueurs, liste de mots",intensite:"Faible"},
{cat:"Jeux calmes",titre:"Le Parcours Sensoriel",desc:"Parcours pieds nus et yeux bandés avec différentes textures au sol : tapis doux, serviettes, papier bulle, gazon synthétique, carton ondulé, sacs de fèves éparpillés. Les joueurs marchent lentement guidés par un partenaire qui les tient par les épaules. À chaque texture, le joueur essaie de deviner. Le joueur avec le plus de bonnes réponses gagne.",duree:"12 min",materiel:"Matériaux de textures variées, bandeaux",intensite:"Faible"},
{cat:"Jeux calmes",titre:"Le Jeu de Concentration",desc:"Les joueurs sont assis en cercle et comptent de 1 à 50 collectivement, un nombre chacun. Pour les multiples de 3, le joueur tape des mains au lieu de parler. Pour les multiples de 5, il tape du pied. Pour les multiples de 3 ET 5, il fait les deux. Si un joueur se trompe, on recommence à 1. L'objectif est d'atteindre 50 sans erreur. Chronométrez le temps pour y arriver.",duree:"10 min",materiel:"Aucun",intensite:"Faible"}"""

content_new = content[:array_content_start] + new_games + '\n' + content[closing_bracket:]

with open(filepath, 'w') as f:
    f.write(content_new)

# Verify
with open(filepath, 'r') as f:
    new_content = f.read()

# Count games in cycle3
cycle3_section = new_content[new_content.index('cycle3:'):]
cycle3_games = cycle3_section[:cycle3_section.index(']')]
game_count = cycle3_games.count('{cat:')
print(f"Cycle3 now has {game_count} games")
print("File updated successfully!")
